### ISSUE TITLE
Error loading  library(RcisTarget.hg19.motifDatabases.20k)

### ISSUE THREAD

**Issue by asmagen** [aertslab/SCENIC#1]
Hello,

I've downloaded RcisTarget.hg19.motifDatabases.20k from the lab website, located it in the 'data' directory created by the workflow published here but calling:

  library(RcisTarget.hg19.motifDatabases.20k) as you do here (or library('data/RcisTarget.hg19.motifDatabases.20k') or install.packages('data/RcisTarget.mm9.motifDatabases.20k ', repos = NULL))

doesn't work.

How can I reproduce the results/follow the rest of the tutorial?

Thanks,
Assaf

**Comment by s-aibar** [comment]
Hello,

Once you download the databases, you have to install them:

`install.packages('downloads/RcisTarget.mm9.motifDatabases.20k_0.1.1.tar.gz', repos = NULL))`

(Note that in your code you have a space at the end and you don't provide the extension. If you want to install it from the uncompressed folder, you might need to add the argument `type="source"`)

Once it is installed successfully, you should be able to load it as a library:

`library(RcisTarget.hg19.motifDatabases.20k)`

As an alternative, you can also unpack the file, and load each of the files manually (e.g. `load("RcisTarget.mm9.motifDatabases.20k/data/dm6_direct_motifAnnotation.RData")`).

I hope you find SCENIC useful! :-)
Regards,
Sara
