### ISSUE TITLE
Issue while running SCENIC step2: regulons ("rankingWrapper")

### ISSUE THREAD

**Issue by sohyon** [aertslab/SCENIC#10]
Hello,

I've read your recent Nature Methods paper with great interest. Our lab studies transcriptional networks, and I am currently trying to apply it to my single-cell data set.

Thanks for the really detailed and easy to follow tutorial. I appreciate it alot.

I've been able to make it as far as part-way through step2: regulons, but then got stuck by an unexpected error which I am not sure how to resolve. When I run the following:

library(RcisTarget)
load("int/2.1_tfModules_forMotifEnrichmet.RData")
org <- "mm9"
if(org=="mm9")
{
library(RcisTarget.mm9.motifDatabases.20k)

Motif rankings (genes x motifs)

data(mm9_500bpUpstream_motifRanking)
data(mm9_10kbpAroundTss_motifRanking)
motifRankings <- list()
motifRankings[["500bp"]] <- mm9_500bpUpstream_motifRanking
motifRankings[["10kbp"]] <- mm9_10kbpAroundTss_motifRanking

Motif annotation (TFs)

data(mm9_direct_motifAnnotation)
direct_motifAnnotation <- mm9_direct_motifAnnotation
data(mm9_inferred_motifAnnotation) # optional
inferred_motifAnnotation <- mm9_inferred_motifAnnotation
}
motifs_AUC <- lapply(motifRankings, function(ranking) calcAUC(tfModules, ranking, aucMaxRank=0.01*nrow(ranking@rankings), nCores=4, verbose=FALSE))**

This is where I get the following error>>>>>>>>>>>>>>>>
Error in (function (classes, fdef, mtable) :
unable to find an inherited method for function ‘getMaxRank’ for signature ‘"rankingWrapper"’
I was reading some of the previous posts and tried to implement the following thinking that ranking Wrapper is the problematic part here:

motifRankings <- rankingWrapper(rankings=mm9_10kbpAroundTss_motifRanking,
rowType="gene", colType="motif", org="mouse", genome="mm9", maxRank = 5000, description="")

However, it is not able to find the function rankingWrapper.....

Any help would be appreciated!

I'm running the script on a HPC cluster, R version 3.4.0, RcisTarget_0.99.5.

Thanks,
Sohyon

**Comment by s-aibar** [comment]
Hello,
You should use RcisTarget version 0.99.0, the current version of RcisTarget in Github is being updated for Bioconductor, which required some changes in the format of the databases, and the new databases (compatible with that version) have not been published yet.
Sorry for the inconvenience!

```
install.packages("http://scenic.aertslab.org/downloads/Rpackages/RcisTarget_0.99.0.tar.gz", repos=NULL)
```

**Comment by sohyon** [comment]
Hello,

Thanks for the help.
That solved the problem above... However the function: motifs_AUC <- lapply(motifRankings, function(ranking) calcAUC(tfModules, ranking, aucMaxRank=0.01*nrow(ranking@rankings), nCores=4, verbose=FALSE))

Is still not working due to a similar problem as listed in a previous issuse:

**Error in calcAUC(tfModules, ranking, aucMaxRank = 0.01 * nrow(ranking@rankings),  :
  Fewer than 80% of the genes in the gene sets are included in the rankings. Check wether the gene IDs in the 'rankings' and 'geneSets' match.**

When I try the suggestions in the previous issue's comments:
>head(motifRankings$`500bp`@rankings$rn)
[1] "0610007C21Rik" "0610007L01Rik" "0610007P08Rik" "0610007P14Rik"
[5] "0610007P22Rik" "0610008F07Rik"
> head(tfModules[[1]])
[1] "1810024B03Rik" "35"            "142"           "149"
[5] "180"           "187"

If I look at the structure of tfModules as generated by:
>tfModules <- setNames(lapply(names(tfModules), function(gsn) {
    tf <- strsplit(gsn, "_")[[1]][1]
    unique(c(tf, tfModules[[gsn]]))
    }), names(tfModules))

>str(tfModules)
List of 4871
 $ 1810024B03Rik_top10perTarget: chr [1:41] "1810024B03Rik" "35" "142" "149" ...
 $ 1810024B03Rik_top50perTarget: chr [1:186] "1810024B03Rik" "10" "15" "35" ...
 $ 1810024B03Rik_top5perTarget : chr [1:22] "1810024B03Rik" "35" "289" "431" ...

Therefore...this makes me think that the geneIDs of the tfModules aren't being properly being put into the right column/list.

Any thoughts on this issue would be appreciated.
On a side note- if I use the wrapper function runSCENIC() should this eliminate these individual issues?

Thanks,
Sohyon

**Comment by s-aibar** [comment]
Hello,
It seems that the results from GENIE3 were read/converted to a factor. Make sure you have the setting **stringAsFactors=FALSE** (on `read.table` or on the global options()...)

**Comment by sohyon** [comment]
Hello,

Thank you for your reply. Indeed that fixed the problem..........
Sorry to bother you again - but hopefully the last question:

Now I am at Part 3.1 
when running the following function: 
aucellRankings <- AUCell.buildRankings(exprMat, nCores=4, plotStats=TRUE)
I get the following error:

**Error in setkeyv(x, cols, verbose = verbose, physical = physical) :
  some columns are not in the data.table: rn**

If I look at the function AUCell.buildRankings more closely, it seems like the setkeyv() requires an argument of designating certain columns... however re-tracing back through the script - I can't find any instance when a "rn" column should have been added to my exprMatrix.

I have not specified "cellLabels" in earlier steps as I do not have any a priori knowledge of what these cells types are. Also, I did not save exprMatrix as a Biobase expression object - as something clashing with assayData and phenoData due to the lack of cellLabels and such were giving me errors...

Thanks ALOT for your help.

**Comment by s-aibar** [comment]
It seems you might have the wrong version of AUCell... (SCENIC is still not updated to work with the version on Bioconductor)

Can you make sure you have 0.99.5, installed with this command?
```
install.packages("http://scenic.aertslab.org/downloads/Rpackages/AUCell_0.99.5.tar.gz", repos=NULL)
```

**Comment by sohyon** [comment]
Hello,

No... unfortunately I don't think that is the problem
I had ver 0.99.5 for AUCell, and I even removed the package and re-installed it with the install.packages code above.

It is still giving this error..

Thank you SO MUCH for your help!

Best,
Sohyon

**Comment by sohyon** [comment]
Hello, sorry to bother you again - but any thoughts on how to fix this error?

Thanks,
Sohyon

**Comment by jgart10** [comment]
I'm also have the same errors as Sohyon - are there plans to fix this?

**Comment by nicolaromano** [comment]
I had the same exact error. It seems simply converting my expression matrix from a sparse dgCMatrix to a non-sparse matrix solved it!

I simply did:

exprMat2 <- matrix(exprMat, ncol = ncol(exprMat), dimnames = list(rownames(exprMat), colnames(exprMat)))

Then passed exprMat2 to the AUCell.buildRankings function.

Hope this may help you guys as well.

**Comment by feifei592** [comment]
> 你好，GENIE3 的结果将被读取/转换为一个**事实**。确保你有设置**stringAsFactors=FALSE**（在`read.table`选项（）...）

Hello!I encountered the same error as "Error in .AUCell_calcAUC(geneSets = geneSets, rankings = rankings, nCores = nCores,  : 
  Fewer than 20% of the genes in the gene sets are included in the rankings.Check wether the gene IDs in the 'rankings' and 'geneSets' match.", but my genes is of character type. Is there any other solution?
