### ISSUE TITLE
There is nothing in https://resources.aertslab.org/cistarget/databases/homo_sapiens/hg19/refseq_r45/mc9nr/gene_based/

### ISSUE THREAD

**Issue by candacelei** [aertslab/SCENIC#102]
I tried to download the human specific RcisTarget database from the resources but there's nothing there.

**Comment by ghuls** [comment]
The main resources site is in the process of being restored, download from the mirror for now: https://resources-mirror.aertslab.org/cistarget/databases/homo_sapiens/hg19/refseq_r45/mc9nr/gene_based/

**Comment by kchowdhary4** [comment]
Hi, the link to the mouse mm9-regions-9species.all_regions.mc9nr.feather is not working from the mirror site. Is there another link to download that from for now? Thank you!

**Comment by ghuls** [comment]
@kchowdhary4 The file was not fully synced to the mirror. Now it is there.
