### ISSUE TITLE
perhaps a bug in: aux_export2scope.R

### ISSUE THREAD

**Issue by fentouxungui** [aertslab/SCENIC#105]
`fileName <- getOutName(scenicOptions, "loomFile")`
should be ahead of 
`if (file.exists(fileName)) 
        stop("File '", getOutName(scenicOptions, "loomFile"), 
            "' already exists.")`

**Comment by sjessa** [comment]
Hi @fentouxungui, I ran into this same error and was wondering if you could share how you solved it? Thank you!

**Comment by fentouxungui** [comment]
> Hi @fentouxungui, I ran into this same error and was wondering if you could share how you solved it? Thank you!

in R console:
`fix(export2scope)`
 find line:
``` r
fileName <- getOutName(scenicOptions, "loomFile")
```
move it ahead of line:
```
if (file.exists(fileName)) stop("File '", getOutName(scenicOptions, "loomFile"), "' already exists.")
``
