### ISSUE TITLE
plot binaryAUC on the reduction plot of a seurat object

### ISSUE THREAD

**Issue by pchiang5** [aertslab/SCENIC#109]
Hello,

Is it possible to extract the binaryAUC data to plot on UMAP or tSNE plots in a seurat object?

I know it is possible to plot regulonAUC based on a previously solved issue. Somehow I could not find the binary data in the 'int' folder of the SCENIC output.

Thanks,
Po

**Comment by chatterjee89** [comment]
Almost a year later... but did this ever get solved?

**Comment by pchiang5** [comment]
Yes. I could do it with the pySCENIC version. Apologies for not updating here and thank you for the good tool.
