### ISSUE TITLE
mm10 RcisTarget databases

### ISSUE THREAD

**Issue by liuyifang** [aertslab/SCENIC#11]
Hi, 
Thank you for your useful SCENIC, can you also provide a mm10 RcisTarget databases, similar to this: 

>  Mouse: install.packages("http://scenic.aertslab.org/downloads/databases/RcisTarget.mm9.motifDatabases.20k_0.1.1.tar.gz", repos=NULL)

mm9 missing some important genes for me. Thanks

Yifang

**Comment by s-aibar** [comment]
Hello,
We are working on creating the databases for mm10 and hg38. I will let you know when they are ready.

**Comment by liuyifang** [comment]
Thank you!
