### ISSUE TITLE
how to apply SCENIC to another species except for human,mouse and fly

### ISSUE THREAD

**Issue by yangmeili1** [aertslab/SCENIC#111]
I read the introduction  part about applying SCENIC into another species. It suggests us to download cis element database and other settings. But I am still confused. Could you give some more details or some specific procedures about it ? Thank you very much.

**Comment by Yichel518** [comment]
Hello!
Have you solved this problem? I have a similar problem for zebrafish recently...

**Comment by s-aibar** [comment]
Hello,

We have now created a tutorial on how to create new databases, which can be used to create databases for new organisms:

https://github.com/aertslab/create_cisTarget_databases

I hope this helps

**Comment by k326xh** [comment]
Hi @s-aibar, 

Thanks for the info!
I've followed the tutorial and generated `zf1.genes_vs_motifs.rankings.feather` for zebrafish. May I ask how to bypass the requirement in `initializeScenic()` that `'org' should be one of: mgi, hgnc, dmel`?

**Comment by sabrinajagot** [comment]
Hi,

I really want use SCENIC on my dataset but i'm also works on another species. I've followed the tutorial too and generated cisTarget_databases but i'm also stopped at the initializeScenic step. Is there any solution ?

**Comment by jiangpuxuan** [comment]
> in `initializeScenic()` that `'org' should be one of: mgi, hgnc, dmel`

I also struck at that step
