### ISSUE TITLE
Generating feather file from motif list

### ISSUE THREAD

**Issue by kashiff007** [aertslab/SCENIC#116]
Dear SCENIC team,

I am working with completely new organisms. I have the annotation file and gene expression, and now I want to use SCENIC to cluster the based on expression and motif present in promoter. I am having hard time with motif database. I have the motif list in promoter region but I am unable to convert it to 'feather' files, which can be used in SCENIC.

I will be grateful if you could help me regarding this issue. 
Thanks

**Comment by s-aibar** [comment]
Hello,

We have now created a tutorial on how to create new databases, which can be used to create databases with new settings and new organisms:

https://github.com/aertslab/create_cisTarget_databases

I hope this helps
