### ISSUE TITLE
Cannot find cell information named 'seuratCluster (it should be a column of the 'cellInfo')

### ISSUE THREAD

**Issue by lelesama** [aertslab/SCENIC#121]

**Comment by lelesama** [comment]
[
![Snipaste_2020-03-11_11-02-46](https://user-images.githubusercontent.com/44505813/76378359-34289b80-6388-11ea-8e0e-f7a9b9abede2.jpg)
![Snipaste_2020-03-11_11-03-15](https://user-images.githubusercontent.com/44505813/76378365-3559c880-6388-11ea-90b8-16b091ea141a.jpg)

](url)

**Comment by martin-jeremy** [comment]
Same error here, how didi you solve it ?

**Comment by SarahMyoblast** [comment]
> > colnames(scenicOptions@inputDatasetInfo$cellInfo)
> > [1] "seuratCluster"
> > class(colnames(scenicOptions@inputDatasetInfo$cellInfo))
> > [1] "character"
> > scenicOptions@inputDatasetInfo$cellInfo
> > seuratCluster
> > AAAGGATAGACATAAC.1             5
> > AAAGGATGTCAAACGG.1            12
> > AAAGGGCGTTATGACC.1            12
> > AAAGTCCCAGATAAAC.1             5
> > AAAGTCCGTCGTTGGC.1            12
> > plotTsne_compareSettings(fileNames, scenicOptions, showLegend=FALSE, varName="seuratCluster", cex=.5)
> > Error in plotTsne_compareSettings(fileNames, scenicOptions, showLegend = FALSE,  :
> > Cannot find cell information named 'seuratCluster (it should be a column of the 'cellInfo').
> 
> @ghuls @KrisDavie @cflerin @steinaerts @juhaa

I have the same error. Did you solve it ?
