### ISSUE TITLE
runSCENIC_2_createRegulons

### ISSUE THREAD

**Issue by 1185958508** [aertslab/SCENIC#134]
when i run this second step: 
runSCENIC_2_createRegulons(scenicOptions, coexMethod=NULL)
RcisTarget: Prunning targets
Error in file(con, "w") : 所有链结都已在运行
how do i resolve this bug?

**Comment by ureyandy2009** [comment]
i meet the same question with you, i guess this is because of the environment(win10) you run r.  you can try run it on python.

**Comment by 1185958508** [comment]
Thank you very much,I will try it.





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"ureyandy2009"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月1日(星期三) 上午9:18
收件人:&nbsp;"aertslab/SCENIC"<SCENIC@noreply.github.com&gt;;
抄送:&nbsp;"qai"<1185958508@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [aertslab/SCENIC] runSCENIC_2_createRegulons (#134)





 
i meet the same question with you, i guess this is because of the environment(win10) you run r.  you can try run it on python.

**Comment by ureyandy2009** [comment]
> Thank you very much,I will try it.
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"ureyandy2009"<notifications@github.com&gt;; 发送时间:&nbsp;2020年7月1日(星期三) 上午9:18 收件人:&nbsp;"aertslab/SCENIC"<SCENIC@noreply.github.com&gt;; 抄送:&nbsp;"qai"<1185958508@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [aertslab/SCENIC] runSCENIC_2_createRegulons (#134) i meet the same question with you, i guess this is because of the environment(win10) you run r. you can try run it on python. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

another way is use r on linux, i'm trying it. and i will tell you if it works.

**Comment by ureyandy2009** [comment]
both scenic on r and pyscenic on python can work in linux. So i guess it's just the environment matters.

**Comment by 1185958508** [comment]
Did you get the ideal results by linux scenic ?&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "aertslab/SCENIC"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月11日(星期六) 上午10:09
收件人:&nbsp;"aertslab/SCENIC"<SCENIC@noreply.github.com&gt;;
抄送:&nbsp;"qai"<1185958508@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [aertslab/SCENIC] runSCENIC_2_createRegulons (#134)





 
both scenic on r and pyscenic on python can work in linux. So i guess it's just the environment matters.

**Comment by ureyandy2009** [comment]
> Did you get the ideal results by linux scenic ?&nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "aertslab/SCENIC" <notifications@github.com&gt;; 发送时间:&nbsp;2020年7月11日(星期六) 上午10:09 收件人:&nbsp;"aertslab/SCENIC"<SCENIC@noreply.github.com&gt;; 抄送:&nbsp;"qai"<1185958508@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [aertslab/SCENIC] runSCENIC_2_createRegulons (#134) both scenic on r and pyscenic on python can work in linux. So i guess it's just the environment matters. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

yes, it works by linux scenic
