### ISSUE TITLE
SHA256sum not matching - wrong feather files?

### ISSUE THREAD

**Issue by CodeInTheSkies** [aertslab/SCENIC#138]
Hello SCENIC team,

I am just beginning to explore SCENIC.  I could successfully download and install the packages and dependencies.  

I have mouse data, and am using mm9 version.  I followed your online instructions to download the feather files:
```
For mouse:

dbFiles <- c("https://resources.aertslab.org/cistarget/databases/mus_musculus/mm9/refseq_r45/mc9nr/gene_based/mm9-500bp-upstream-7species.mc9nr.feather",
"https://resources.aertslab.org/cistarget/databases/mus_musculus/mm9/refseq_r45/mc9nr/gene_based/mm9-tss-centered-10kb-7species.mc9nr.feather")
# mc9nr: Motif collection version 9: 24k motifs
```

But the SHA256sums do not match for the above files with what you have given here:
https://resources.aertslab.org/cistarget/databases/sha256sum.txt

I am getting the sums as:

mm9-500bp-upstream-7species.mc9nr.feather:
2f93fc442f3001979321a2c097a4e32277c5e6cff7c1cf8553da1a502ca5b8e5

mm9-tss-centered-10kb-7species.mc9nr.feather:
5ee60e2d9dbc156740cab4f142dc3368016427d687d4daf38a91eedefd51f571

Also, I notice that the sizes of the above two feather files are exactly the same.  Is that how it is supposed to be?

Is there anything wrong here?  Am I downloading the wrong files?

I would really like to try and use your software, and so would appreciate your guidance.

Many thanks.

**Comment by XiaofeiSunUCSF** [comment]
Same here. I have the same feather Sums as what you got

**Comment by CodeInTheSkies** [comment]
Would be nice if the authors actually respond.

**Comment by ghuls** [comment]
This are the checksums on the server:
```
$ sha256sum mm9-500bp-upstream-7species.mc9nr.feather mm9-tss-centered-10kb-7species.mc9nr.feather
bba21fb3b7e96ebfb97d31a59d661678973073b77b1c3e7a1bb2e49114a82425  mm9-500bp-upstream-7species.mc9nr.feather
ad7ee54883f5964c0e699e5c5bab08589eb0626599297085197cb6f80c5e12fc  mm9-tss-centered-10kb-7species.mc9nr.feather
```

Filesizes:
```
1081248976 mm9-500bp-upstream-7species.mc9nr.feather
1081248976 mm9-tss-centered-10kb-7species.mc9nr.feather
```

```
# Try downloading with cURL.
curl -O "https://resources.aertslab.org/cistarget/databases/mus_musculus/mm9/refseq_r45/mc9nr/gene_based/mm9-tss-centered-10kb-7species.mc9nr.feather"

# Or try downloading with cURL from the mirror.
curl -O "https://resources-mirror.aertslab.org/cistarget/databases/mus_musculus/mm9/refseq_r45/mc9nr/gene_based/mm9-tss-centered-10kb-7species.mc9nr.feather"
****
