### ISSUE TITLE
What are the numbers in brackets in the regulon names?

### ISSUE THREAD

**Issue by CodeInTheSkies** [aertslab/SCENIC#142]
Hi there,

What do the numbers within the regulon names in the AUC matrix represent?

Example, Gtf2b_extended (621g) ?

Would appreciate a reply asap.  

Thank you very much!

**Comment by yaolutian** [comment]
I have the same question, and why I do not have the "_extended (XXg)" after running with pySCENIC?

Thanks!

**Comment by s-aibar** [comment]
The numbers in parenthesis in the regulon names indicate the number of genes in the regulon (i.e. "Dlx (35g)").
This is now clarified in the Vignette and the FAQ.
