### ISSUE TITLE
RcisTarget motif database on Fly, BDGP 6

### ISSUE THREAD

**Issue by abmmki** [aertslab/SCENIC#15]
Hi, 

Could you share RcisTarget motif database on Fly. We are using latest Drosophila Melanogaster genome version 6 (BDGP). Ensembl 90.

Thanks in advance,

**Comment by abmmki** [comment]
Any update??

**Comment by s-aibar** [comment]
Hello,
The drosophila databases are still not publicly available. We plan to release them within a few months, as part of the paper by [Davie et al.](https://www.biorxiv.org/content/early/2017/12/21/237420)). 
If you need access earlier, please [contact us](https://aertslab.org/#contact) by e-mail.
