### ISSUE TITLE
Why getting error in executing open_loom command

### ISSUE THREAD

**Issue by inayat45shaikh** [aertslab/SCENIC#151]
Hello,
I am trying executing example datasets in SCENIC R workflow, but getting error which loading loom file
here is the command i am using
loomPath <- system.file(package="SCENIC", "examples/mouseBrain_toy.loom")
library(SCopeLoomR)
loom <- open_loom(loomPath, mode="r")
Error in x$create_attr(which, robj = value) : HDF5-API Errors:
    error #000: ../../../src/H5A.c in H5Acreate2(): line 267: no write intent on file
        class: HDF5
        major: Invalid arguments to routine
        minor: Write failed

could anyone help me fixing this issue.

Thanks
Inayat

**Comment by Danne1210** [comment]
I encountered the same problem.

**Comment by s-aibar** [comment]
Can you try whether the error persists by setting `mode="r+"`?

**Comment by tqh003** [comment]
> 

I tried mode="r+", the error persisted.

**Comment by tqh003** [comment]
I encountered the same problem, then tried mode="r+" as s-aibar suggested, then the error became as follows:
Error in self$flush() : HDF5-API Errors:
    error #000: D:/a/rtools-packages/rtools-packages/mingw-w64-hdf5/src/hdf5-1.8.16/src/H5F.c in H5Fflush(): line 727: unable to flush mounted file hierarchy
