### ISSUE TITLE
Question for batch effect from input data

### ISSUE THREAD

**Issue by lh12565** [aertslab/SCENIC#159]
Hi,

I found the input of SCENIC is a count matrix. However, I have some samples with batch effect and can I use the directly merged count matrix as input? If not, I tried to run each sample individually, but the output is different, such as LEF1 (101g) for one sample and LEF1_extend (1034g) for another. How do I integrate it after that? Thanks!

**Comment by s-aibar** [comment]
Dear @lh12565 : 

You can use the batch-corrected matrix as input to SCENIC. It will indeed provide different results than running it on each sample individually, but the interpretation, and how to merge the networks depends on your specific dataset...
