### ISSUE TITLE
Error when using calcAUC (could not find function "matrixWrapper") 

### ISSUE THREAD

**Issue by justinesjw** [aertslab/SCENIC#16]
Hi, 

I have been following the tutorial on github and currently stuck in Step2_Regulons calcAUC()
I've tried running it a few times using the code below:

`motifs_AUC <- lapply(motifRankings, function(ranking) calcAUC(tfModules, ranking, aucMaxRank=0.01*nrow(ranking@rankings), nCores=12, verbose=FALSE))`

but I seem to run into the same error 

> Error in matrixWrapper(matrix = aucMatrix, rowType = "gene-set", colType = "motif",  :
  could not find function "matrixWrapper"

I'm running it on 
    - Linux 64bit (CentOS 6.5) 
    - R version 3.4.1
    - RcisTarget_0.99.0
    - AUCell_1.0.0

Any idea on how can I fix this error?

Thanks, 
Justine

**Comment by s-aibar** [comment]
The current version of SCENIC (v0.1.6) requires AUCell 0.99.5. (Some functions were renamed on version 1.0).
To correct the error, it should be enough with removing the current AUCell installation (`remove.packages()`) and running:
```
install.packages("http://scenic.aertslab.org/downloads/Rpackages/AUCell_0.99.5.tar.gz", repos=NULL)
```
Regards,
Sara

**Comment by justinesjw** [comment]
Thanks for the speedy reply :+1: 
That solved the problem!

Thanks!!

**Comment by yasin-chop** [comment]
Hi,
I have the same problem, but removing AUCell 1.0 and loading AUCell 0.99.5 did not solve the problem. I still get the same error. Do you have any idea about it?
Thanks
