### ISSUE TITLE
calculate TF  using the differential expression genes 

### ISSUE THREAD

**Issue by wtj505531480** [aertslab/SCENIC#162]
Thanks for the SCENIC, could I use the differential expression genes as the input of the SCENIC?thank you

**Comment by s-aibar** [comment]
Yes, there are two main options that I can think of: 

A) You could filter the input matrix to include only the differentially expressed genes (but beware that that will likely reduce a lot the sensitivity of the networks, see the Nature Methods 2017 paper).

B) If you are only intererested on potential regulators, you can just use RcisTarget on the differentially expressed genes. That will provide potential TFs/motifs as regulators for those genes (and therefore, the cell type or state). 
That analysis might already be enough, but if you want to get a more complete "SCENIC-like" analysis, you also check which of those genes are regulated by each TF (you can see the code in the detailed vignette for Step 2). That will be kind of a manual regulon/network, and of course, you can then score it on your cells with AUCell (detailed vignette for step 3).

**Comment by wtj505531480** [comment]
Thanks for your reply !!
