### ISSUE TITLE
How to use pyscenic output draw RSS result Binary heatmap

### ISSUE THREAD

**Issue by siqi-zZ** [aertslab/SCENIC#164]
Hi, It is helpful for the tool !!!  Can I just use pyscenic output result got your jupyter tuturial figure? like below one
![image](https://user-images.githubusercontent.com/21080145/96534090-a4ee4980-12c1-11eb-89b1-9fe91c1369d8.png)
![image](https://user-images.githubusercontent.com/21080145/96534113-b0da0b80-12c1-11eb-9496-ada51a2bc1b7.png)

**Comment by cflerin** [comment]
Hi @siqi-zZ ,

These figure are from two notebooks: [here, for the PBMC RSS plot](https://github.com/aertslab/SCENICprotocol/blob/master/notebooks/PBMC10k_downstream-analysis.ipynb), and the [heatmap for the cancer data here](https://github.com/aertslab/SCENICprotocol/blob/master/notebooks/SCENIC%20Protocol%20-%20Case%20study%20-%20Cancer%20data%20sets.ipynb). All of the commands to generate those figure are included in the notebooks. You should be able to substitute you own data with some modifications and generate similar figures. If you're having a specific problem, you can ask further here.
