### ISSUE TITLE
dotheatmap.R not found when plotRSS(rss)

### ISSUE THREAD

**Issue by zezhuo** [aertslab/SCENIC#166]
Hi @s-aibar , Thanks for the nice package. I got a problem when running plotRSS(rss). Attached error messages. Looking forwards to your suggestion.

```
> rssPlot <- plotRSS(rss)
Showing regulons and cell types with any RSS > 0.01 (dim: 25x7)
Error in file(filename, "r", encoding = encoding) : 
  cannot open the connection
In addition: Warning message:
In file(filename, "r", encoding = encoding) :
  cannot open file '/ddn1/vol1/staging/leuven/stg_00002/lcb/saibar/Projects/aux_scripts/dotheatmap.R': No such file or directory
```

The other issues that I found are about the memory, multiple cores, and dependencies. 

Running out of memory can be solved by reducing cores:
```
#### Run SCENIC ####
dbs <- c("hg38__refseq-r80__500bp_up_and_100bp_down_tss.mc9nr.feather", "hg38__refseq-r80__10kb_up_and_down_tss.mc9nr.feather")
names(dbs) <- c("500bp", "10kb")
scenicOptions <- initializeScenic(org="hgnc", dbDir="../dbs", dbs = dbs, datasetTitle="chons", nCores=8)
```

Multiple cores issue of runSCENIC_3 is solved by using one core only.
```
scenicOptions@settings[["nCores"]] <- 1
scenicOptions <- runSCENIC_3_scoreCells(scenicOptions, exprMat_log)
```

The following packages are required in my case
```
#### Load library ####
# Sys.setenv(LANG="en_US.UTF-8")
library(SCENIC)
library(BiocParallel)
library(SCopeLoomR)
library(RColorBrewer)
library(KernSmooth)
library(Seurat)
library(dplyr)
```

Wish your next updates make the package more friendly to the users.

Regards,
Nelson

**Comment by apaikari** [comment]
cannot open file '/ddn1/vol1/staging/leuven/stg_00002/lcb/saibar/Projects/aux_scripts/dotheatmap.R': No such file or directory

**Comment by liuyifang** [comment]
same issue
`Showing regulons and cell types with any RSS > 0.01 (dim: 38x14)
cannot open file '/ddn1/vol1/staging/leuven/stg_00002/lcb/saibar/Projects/aux_scripts/dotheatmap.R': No such file or directoryError in file(filename, "r", encoding = encoding) : 
  cannot open the connection`

**Comment by lelesama** [comment]
same issue

**Comment by vagabond12** [comment]
same issue

**Comment by Coke-Zhang** [comment]
Yeah. I have the same error. So how to resolve them ?

**Comment by Roger-GOAT** [comment]
same issue!!!

**Comment by dandata123-tech** [comment]
I get the same problem,Have any body solve it ?

**Comment by dandata123-tech** [comment]
Guys,I found that we should update the SCENIC
devtools::install_github("aertslab/SCENIC",force = TRUE)
and the outdate RSQLite is the main reason that make this question
