### ISSUE TITLE
File 'int/1.4_GENIE3_linkList.Rds' does not exist

### ISSUE THREAD

**Issue by EAC-T** [aertslab/SCENIC#173]
Hello everyone,

I'm trying to run the tutorial on my data. I have a seurat object and I did this:

## Get data from Seurat object:
exprMat<-GetAssayData(seurat, slot = "counts")
exprMat<-as.matrix(exprMat)
cellInfo <- data.frame(seuratCluster=Idents(seurat))
### Initialize settings
scenicOptions <- initializeScenic(org="mgi", dbDir="C:/Users/name/Desktop/cisTarget_databases", nCores=10)
### Co-expression network
genesKept <- geneFiltering(exprMat, scenicOptions)
exprMat_filtered <- exprMat[genesKept, ]
runCorrelation(exprMat_filtered, scenicOptions)
exprMat_filtered_log <- log2(exprMat_filtered+1) 
runGenie3(exprMat_filtered_log, scenicOptions)
##Finished running GENIE3

### Build and score the GRN
exprMat_log <- log2(exprMat+1)
scenicOptions@settings$dbs <- scenicOptions@settings$dbs["10kb"] 
scenicOptions <- runSCENIC_1_coexNetwork2modules(scenicOptions)

Error in .local(object, ...) : 
  File 'int/1.4_GENIE3_linkList.Rds' does not exist.

I'm getting this error. 

If I do: getInName(scenicOptions) I can see the genei3ll  fileName "int/1.4_GENIE3_linkList.Rds"

Any help will be greatly appreciate it!
Thank you

**Comment by liaoshengyou** [comment]
you shoud use the newst SCENIC version, read SCENIC_Running.html pipeline.
