### ISSUE TITLE
do you have mm10 and hg38?

### ISSUE THREAD

**Issue by tanpuekai** [aertslab/SCENIC#18]
hg19 and mm9 seem slightly outdated.

**Comment by jfreimer** [comment]
I'm also wondering if you have mm10 annotations?

**Comment by ghuls** [comment]
They are available now for a while at: https://resources.aertslab.org/cistarget/

**Comment by ChickenWangSY** [comment]
Hi，
I'm leaning the SECNIC for human transcriptome . and I want to use the hg38. When I run 

> Initialize SCENIC settings
`org="hgnc" # or hgnc, or dmel
dbDir="F:\\BGI\\tools\\SCENIC\\database\\human" # RcisTarget databases location
myDatasetTitle="SCENIC analysis on human" # choose a name for your analysis
scenicOptions <- initializeScenic(org=org, dbDir=dbDir, datasetTitle=myDatasetTitle, nCores=20) 
`
the error is "Warning message:
In initializeScenic(org = org, dbDir = dbDir, datasetTitle = myDatasetTitle,  :
  RcisTarget databases not found. Please, initialize them manually."

emmm, there two files in the file path "F:\\BGI\\tools\\SCENIC\\database\\human", 
"hg38__refseq-r80__10kb_up_and_down_tss.mc9nr.feather"
"hg38__refseq-r80__500bp_up_and_100bp_down_tss.mc9nr.feather"

right , then I checked the function `initializeScenic` ,and I found that the `defaultDbNames` is the two ".feather" files on hg19 ,
"hg19-500bp-upstream-7species.mc9nr.feather"
"hg19-tss-centered-10kb-7species.mc9nr.feather"
so, if I want to use the hg38 annotation files. do I need to change the defaultdbnames? or other methods?
looking forward to your reply!

**Comment by s-aibar** [comment]
Hello, 

Yes, to use different databases just modify the `scenicOptions@settings$dbs` (and `scenicOptions@settings$db_mcVersion <- "v9"` if needed).

Running GENIE3 is usually quite long, thats why we created GRNBoost (and recommend it for most datasets...) :)

**Comment by sylestiel** [comment]
Can anyone assist me with the scripts needed to read in the mm10 specific feather files? Something is amiss.

**Comment by sylestiel** [comment]
@jfreimer 

Hi, 

Were you able to call in the mm10 feathers instead of mm9 in Scenic.

If so can you tell me how to modify my scenicOptions so that the mm10 files may be recognized?

Thanks!
