### ISSUE TITLE
How to run SCENIC for chimp data?

### ISSUE THREAD

**Issue by weishwu** [aertslab/SCENIC#182]
Hi,

I've seen papers in which they ran SCENIC on non-human primate sequencing data using human reference:
https://www.nature.com/articles/s41467-020-15997-0#Sec8
https://www.cell.com/cell/pdf/S0092-8674(20)30056-8.pdf

I currently want to run SCENIC on chimpanzee 10x data and wonder if I need to modify any of the reference data files used by SCENIC and how, such as:
1. refseq-r80__10kb/500bp_up_and_down_tss.mc9nr.feather
2. TF file
3. Motif database

Thanks,

**Comment by s-aibar** [comment]
Hello,
We have now some tutorials to create databases with new settings: https://github.com/aertslab/create_cisTarget_databases
These can also be used for new organisms.

I hope this helps
