### ISSUE TITLE
Could not find function "plotTsne_rgb"

### ISSUE THREAD

**Issue by AAA-3** [aertslab/SCENIC#187]
Following the vignette:

Code: `cellCol <- plotTsne_cell(scenicOptions, regulonNames, aucType="AUC", aucMaxContrast=0.6)`

Error: 

```
Error in plotTsne_rgb(scenicOptions, regulonNames, aucType = "AUC", aucMaxContrast = 0.6) : 
  could not find function "plotTsne_rgb"
```

The command  doesn't seem to exist...
![image](https://user-images.githubusercontent.com/68068335/115588771-6157b500-a2cf-11eb-903f-f8891081f291.png)
@s-aibar could you advise?

**Comment by jiangfuqing** [comment]
Hi, I meet the same question, have you fixed it now?

**Comment by AAA-3** [comment]
Nope - not sure how quite to address it  - I came across the [source code ](https://github.com/aertslab/SCENIC/blob/master/R/plotTsne_rgb.R) but when I copied that in it still wouldn't work. Try it anyway hopefully it works for you...

**Comment by morganee261** [comment]
Hello, it seems like it was replaced by this function : plotEmb_rgb
plotEmb_rgb(scenicOptions,regulonNames = regulonNames,aucType = "Binary",aucMaxContrast = 1,offColor = "lightgray",showLegend = F) 
this line works for me.

Morgane

**Comment by AAA-3** [comment]
> Hello, it seems like it was replaced by this function : plotEmb_rgb
> plotEmb_rgb(scenicOptions,regulonNames = regulonNames,aucType = "Binary",aucMaxContrast = 1,offColor = "lightgray",showLegend = F)
> this line works for me.
> 
> Morgane

Oh yep! Sorry I forgot to update the thread - yes, looks like the function is deprecated and replaced with plotEmb_rgb. The source code is found on GitHub but the vignette for Running Scenic is not updated for the 2021 release of the package.

Also, for me, I used `SCENIC::plotEmb_rgb()` because R would keep referring to AUCell package which has different inputs!
