### ISSUE TITLE
runCorrelation matrix error

### ISSUE THREAD

**Issue by AAA-3** [aertslab/SCENIC#191]
Hello :)

I imported me seurat file into SCENIC:
```
#Importing data from Seurat RDS file
exprMat <- GE@assays[["RNA"]]@counts
cellInfo <- GE@meta.data[colnames(exprMat), "sample", drop=F]
cellInfo <- data.frame(cellInfo)
cbind(table(cellInfo$sample))
dir.create("int")
saveRDS(cellInfo, file="int/cellInfo.Rds")
```
and then ran the filtration based on the solution provided in https://github.com/aertslab/SCENIC/issues/90#issue-473703158

I am attempting to run a correlation using the `runCorrelation(exprMat_filtered, scenicOptions) `command but I keep getting an error claiming `Error in t.default(exprMat_filtered) : argument is not a matrix`. This is despite the global environment window stating that it is: 
![Screenshot from 2021-04-27 11-44-01](https://user-images.githubusercontent.com/68068335/116223481-d9026580-a74f-11eb-8d8c-ea68ed6310f2.png)

I looked at the source code https://github.com/aertslab/SCENIC/blob/master/R/runCorrelation.R but am not sure how to manipulate it to proceed. Any ideas?

**Comment by AAA-3** [comment]
Update: I forced the file to be read as a matrix by adding: `exprMat_filtered <- as.matrix(exprMat_filtered)` before the `runCorrelation() `command. Continuing on with the GENIE3 pipeline. Not sure what the cause of this error was but at least we have a solution for those who also run into this problem :)

**Comment by zh-zhang1984** [comment]
However, sometimes the `exprMat` is very large and `as.matrix` function will report error:
```
> exprMat <- Matrix::as.matrix(Sepsis_seurat@assays$RNA@data)
Error in asMethod(object) : 
  Cholmod error 'problem too large' at file ../Core/cholmod_dense.c, line 102
```
