### ISSUE TITLE
RSS Plot not selecting the dseired data (out of bounds error)

### ISSUE THREAD

**Issue by AAA-3** [aertslab/SCENIC#194]
Trying to run the following code
```
#Cell-type specific regulators (based on the Regulon Specificity Score (RSS) 
regulonAUC <- loadInt(scenicOptions, "aucell_regulonAUC")
rss <- calcRSS(AUC=getAUC(regulonAUC), cellAnnotation=cellInfo[colnames(regulonAUC), "genotype"])
rssPlot <- plotRSS(rss)
plotly::ggplotly(rssPlot$plot)
```
and keep getting this error
```
> rssPlot <- plotRSS(rss) # seems to be plotting by sample isntead of genotype
Showing regulons and cell types with any RSS > 0.01 (dim: 0x0)
Error in tmp[, i] : subscript out of bounds
```
The graph is still produced but it is not by `"genotype"` like I specified, but seems to rather be by `"sample"` - see below:
![image](https://user-images.githubusercontent.com/68068335/116694581-becebe80-a9bf-11eb-9a7e-eb64df83efc4.png)

![image](https://user-images.githubusercontent.com/68068335/116694476-a199f000-a9bf-11eb-95c1-5e2e140d759b.png)

Any idea how to plot the graph using genotype instead of sample?

**Comment by siqi-zZ** [comment]
Hi, I had a similar question, I had 6 group at regulonAUC, but the plotrss only shows 4. After check the plotrss table I found others 2 group had 0 TF
![image](https://user-images.githubusercontent.com/21080145/141877244-6a74df82-bf9c-46cb-bc83-07cfa15df987.png)
. Is that mean plotRss choose some significance TF? Or can I increase the display of these TFs by changing the threshold adjustment?
![image](https://user-images.githubusercontent.com/21080145/141877103-c1c28e7d-5bae-4836-89bf-aedbbfa5b120.png)

**Comment by yoeHuuui** [comment]
I guess, it may be caused by the parameter `zThreshold`  in `plotRSS` function. You can try to decrease the value of it.
