### ISSUE TITLE
why not make into one single command line? not very user-friendly

### ISSUE THREAD

**Issue by tanpuekai** [aertslab/SCENIC#20]
hi there,

I run thru the codes. Wondering why we have to copy and paste so much codes, when you can actually hide all of the middle processes, and package them into one single command line?

These days, good bioinformatics software is user-friendly. should only define the input, and explain the output very well, and hide all of the controlling details in the command line's parameters. Pretty sure your codes can be packaged that way.

The current way is not tidy, not well structured. Also not outputting enough running info even when VERBOSE set to TRUE.

Chancellor

**Comment by vthaker** [comment]
Hi Chancellor,

Your request is genuine, sincere and appropriate.
It sounds like you can think of ideas that other folks have either not thought, or not implemented.
In the interest of community raising the bar for everything, may be a good idea for you to send in your code to incorporate with the changes you suggest?

Many thanks
Vidhu

**Comment by tanpuekai** [comment]
hi there,

hope i have not offended you, not what i intended to.
just pure user-side experience comments.

Chancellor

**Comment by vthaker** [comment]
No offense taken.

I am not the builder of this project, just a mere user myself.
Strong believer of understanding shortcomings, taking feedback, and rolling up sleeves to contribute to improve them.
Thanks
Vidhu
