### ISSUE TITLE
Comparing RAS scores between independent runs

### ISSUE THREAD

**Issue by jakalssj3** [aertslab/SCENIC#202]
I have divided my cells into two sub-populations for which I have run SCENIC analysis independently. Can I directly compare RAS scores for a given regulon between two different runs (I know these may have different number of genes between the two runs)?

**Comment by s-aibar** [comment]
The regulon scores are mostly meant to compare the activity of a regulon across the cells... 
i.e. it should be OK to score both versions of regulons across the two subsets of cells, to see in which cells it is more enriched...
