### ISSUE TITLE
Generation of Gene Expression Matrix for Scenic when starting with Cell Ranger

### ISSUE THREAD

**Issue by sylestiel** [aertslab/SCENIC#206]
Hi,

         Having read in the 10x Cell Ranger output how do we proceed to generate the exprMat if what we have is a sparse Matrix of class "dgCMatrix"?

Do we run part of the assay using Seurat before going into Scenic?

Also can we use Multiomic scATAC+GEX data from Cell ranger to process it in Scenic?

Thanks!

**Comment by s-aibar** [comment]
Dear @sylestiel ,

We are working on a pipeline that will allow to analyze simultaneously gene expression and scATAC data, but it is not public yet.
Feel free to follow https://github.com/aertslab to get notified of updates...

Regards
