### ISSUE TITLE
runSCENIC_2_createRegulons error

### ISSUE THREAD

**Issue by ivonyao** [aertslab/SCENIC#209]
I have been stuck at this step, with an error as follows, not sure how to solve the problem. I have tried different computers and different downloads of the database.

Error in runSCENIC_2_createRegulons(scenicOptions) : 
  It is not possible to load the following databses: 
mm9-500bp-upstream-7species.mc9nr.feather

**Comment by ryrl970311** [comment]
I met the same error in load hg38__refseq-r80__10kb_up_and_down_tss.mc9nr.feather. Have you solved it ?

**Comment by s-aibar** [comment]
You probably need to set the path to the databases when initializing the run...
