### ISSUE TITLE
Do you have any suggestions about SCENIC for other species other species ?

### ISSUE THREAD

**Issue by weipingz** [aertslab/SCENIC#225]
Thank you very much for creating this method. Recently, I  need to use SCENIC on other species. I also looked at the previous issues. Is there a proper way to solve this problem now ? Thanks for your time !

**Comment by s-aibar** [comment]
Yes, there is now a tutorial on how to create new motif databases, which you can use to create them for your species of interest: https://github.com/aertslab/create_cisTarget_databases
