### ISSUE TITLE
Questions?

### ISSUE THREAD

**Issue by s-aibar** [aertslab/SCENIC#236]
> Github issues (this forum) should only be used to report **bugs**, unexpected errors, or feature requests for the **R implementation** :-)

For **questions** about using SCENIC, please use the [Discussions](https://github.com/aertslab/SCENIC/discussions/).

* Note that some common questions are already addressed in the [FAQ](https://github.com/aertslab/SCENIC/blob/master/vignettes/FAQ.md)

**Comment by ghuls** [comment]
SCENIC is deprecated software, use pySCENIC instead:

Container versions are available:
https://pyscenic.readthedocs.io/en/latest/installation.html#docker-podman-and-singularity-apptainer-images
