### ISSUE TITLE
Differences in data scales

### ISSUE THREAD

**Issue by topherconley** [aertslab/SCENIC#24]
Hi, 

The input to GENIE3 allows for a log-scale normalized UMI counts; however, step 3.1 uses just the normalized counts as in put. The wrapper function takes the log-scale normalized UMI counts as input, but never requires or complains about not having the normalized UMI counts. 

Does this matter? For example, I see that the 'nGene' per cell calculation of 3.1 assumes there are no negative values, but we know this is likely not the case with log-scaled values. 

Thank you in advance,
Chris

**Comment by s-aibar** [comment]
(This is now addressed in the Vignette)
