### ISSUE TITLE
Cell identity tutorial

### ISSUE THREAD

**Issue by hekselman** [aertslab/SCENIC#25]
Dear team. Great tutorial and package!
When I create the regulon heatmaps, is there a way to add my previously determined identities of each cell?
I didn't understand my way around the "cellInfo" and "colVars" objects. What would be most efficient in this phase, where I have a vector of identities of each cell (from another source) and the matrix of relevant regulons?
Thanks in advance, Idan.

**Comment by hekselman** [comment]
Managed to overcome this problem! :)

**Comment by lelesama** [comment]
> Managed to overcome this problem! :)

Hello, I have the same problem. could you please let us know how you overcomed it? Thank you
