### ISSUE TITLE
GENIE3 installation link is not working

### ISSUE THREAD

**Issue by cpalmtree** [aertslab/SCENIC#26]
Hi,

When trying to install GENIE3 using the installation links it gives a 404 error. 

trying URL 'http://bioconductor.org/packages/release/bioc/src/contrib/GENIE3_1.0.0.tar.gz'
Warning in install.packages :
  cannot open URL 'http://bioconductor.org/packages/release/bioc/src/contrib/GENIE3_1.0.0.tar.gz': HTTP status was '404 Not Found'
Error in download.file(p, destfile, method, mode = "wb", ...) : 
  cannot open URL 'http://bioconductor.org/packages/release/bioc/src/contrib/GENIE3_1.0.0.tar.gz'

**Comment by s-aibar** [comment]
Hello, 
Indeed, a new version of the packages is now available in Bioconductor. The hew URL is:
http://bioconductor.org/packages/release/bioc/src/contrib/GENIE3_1.2.0.tar.gz

(Sorry for the trouble, I'm working on an update SCENIC to use the new versions. It will be released within a few days)
