### ISSUE TITLE
Error on runSCENIC_3_scoreCells

### ISSUE THREAD

**Issue by galib36** [aertslab/SCENIC#27]
I am getting the following error when I run runSCENIC_3_scoreCells, could you please tell me how to fix it.

runSCENIC_3_scoreCells(scenicOptions, exprMat_filtered)
22:36   Step 3. Analyzing the network activity in each individual cell

Number of regulons to evaluate on cells: 415
Biggest (non-extended) regulons:
         EGR1 (4140g)
         ELF1 (4100g)
         ATF3 (4088g)
         ETS2 (3401g)
         BCLAF1 (2974g)
         ETV6 (2873g)
         POLR2A (2530g)
         ETV5 (2436g)
         ELK3 (1792g)
         REL (1741g)
Quantiles for the number of genes detected by cell:
(Non-detected genes are shuffled at the end of the ranking.Keep in mind when choosing the threshold for calculating the AUC).
    min      1%      5%     10%     50%    100%
 159.00  325.66  717.30  842.20 1863.00 5663.00
Using 2 cores.
Using 2 cores.
Error in sample.int(length(x), size, replace, prob) :
  cannot take a sample larger than the population when 'replace = FALSE'

**Comment by s-aibar** [comment]
The error is now fixed (sorry, I had not taken into account that some datasets might have fewer than 500 cells). If you re-install SCENIC package it should now work.
