### ISSUE TITLE
Step 2 Error

### ISSUE THREAD

**Issue by tnbach** [aertslab/SCENIC#28]
Hi,

I kept running into the error: failed to stop 'SOCKcluster' cluster: ignoring SIGPIPE signal while running step 2 SCENIC. This error comes after the RcisTarget: Adding motif annotation. Could you please advise me a way to go around it?

Thanks

**Comment by s-aibar** [comment]
Hello,

That error seems to happen in some linux machines when using multiple cores and some of the processes runs out of memory. The general recommendation -e.g. similar error in other packages- is to use fewer cores (maximum your number of cores-1, but lower if the processes use a lot of memory). 

In this case, the function to add the motif annotation (RcisTarget::addMotifAnnotation) uses BiocParallel::bplapply. You probably need to adjust the settings for BiocParallel. You can do some tests with this code:
```
library(BiocParallel)
registered() # your current settings
system.time(bplapply(1:1000, sqrt))

register(MulticoreParam(workers = 10), default = TRUE)
# or: register(SerialParam(), default = TRUE)
system.time(bplapply(1:1000, sqrt))
```

Plesase, let me know whether this helps,
Sara

**Comment by tnbach** [comment]
Thank you very much! It took awhile to run but it worked..Hooray!
