### ISSUE TITLE
Error in runSCENIC_2_createRegulons: object 'indexCol' not found

### ISSUE THREAD

**Issue by monnneee** [aertslab/SCENIC#290]
Hello, thanks for this great tool!

When I run 'runSCENIC_2_createRegulons' with SCENIC version 1.3.0, I got the following error:

scenicOptions <- runSCENIC_2_createRegulons(scenicOptions, coexMethod=c("top5perTarget"))
10:56   Step 2. Identifying regulons
Error in sapply(getDatabases(scenicOptions), dbLoadingAttempt, dbIndexCol = indexCol) :
  object 'indexCol' not found

I didn't find 'indexCol' in the script "SCENIC/R/runSCENIC_2_createRegulons.R".

**Comment by ly55** [comment]
I also encountered the same problem. How did you solve it? Thank you

**Comment by mw201608** [comment]
Same here with the latest version from github. The old release SCENIC_1.1.2.tar.gz is working fine.

**Comment by BIOBRICK** [comment]
I think I know why.....well might know.....after about 2 hours debugging......
After I installed SCENIC in R the code in runSCENIC_2_createRegulons changed (don't know how and why.....) 

--source codes are  as below: line 47:
loadAttempt <- sapply(getDatabases(scenicOptions), dbLoadingAttempt)

yet after installed, the codes are as below......line 38-39:
loadAttempt <- sapply(getDatabases(scenicOptions), dbLoadingAttempt, dbIndexCol = indexCol)

so easy to understand why we get this error.....
I don't know how and why that things becomes like this, but I think this is the main problem.
**So just manually source "runSCENIC_2_createRegulons.R" in this repo and re-run runSCENIC_2_createRegulons step. On our data this works fine.**

**Comment by s-aibar** [comment]
Hello,

`indexCol` was added to RcisTarget in the last Bioconductor update. To avoid the error you have to keep consistent versions, i.e. : 

- Option A (recommended): Install the latest versions of R (4.2) and Bioconductor (3.15, released a few days ago). This will lead to RcisTarget (1.16), which should be consistent with SCENIC 1.3. 

- Option B: If you are not able (or don't want) to update R/Bioconductor, then you need to install one of the previous versions of SCENIC available in the "tags" section (See the "setup" vignette).

Please let me know if you still have issues after confirming you have the matching versions,
Sara

**Comment by BIOBRICK** [comment]
> Hello,
> 
> `indexCol` was added to RcisTarget in the last Bioconductor update. To avoid the error you have to keep consistent versions, i.e. :
> 
>     * Option A (recommended): Install the latest versions of R (4.2) and Bioconductor (3.15, released a few days ago). This will lead to RcisTarget (1.16), which should be consistent with SCENIC 1.3.
> 
>     * Option B: If you are not able (or don't want) to update R/Bioconductor, then you need to install one of the previous versions of SCENIC available in the "tags" section (See the "setup" vignette).
> 
> 
> Please let me know if you still have issues after confirming you have the matching versions, Sara

Thanks a lot, I tried option A on example data and works fine. I guess this problem is solved for me LOL.

**Comment by hk106609620** [comment]
> Hello,
> 
> `indexCol` was added to RcisTarget in the last Bioconductor update. To avoid the error you have to keep consistent versions, i.e. :
> 
> * Option A (recommended): Install the latest versions of R (4.2) and Bioconductor (3.15, released a few days ago). This will lead to RcisTarget (1.16), which should be consistent with SCENIC 1.3.
> * Option B: If you are not able (or don't want) to update R/Bioconductor, then you need to install one of the previous versions of SCENIC available in the "tags" section (See the "setup" vignette).
> 
> Please let me know if you still have issues after confirming you have the matching versions, Sara

Sorry,,,I still have this problem with the R (4.2) , Bioconductor (3.15), 

>

**Comment by yixugalaxy** [comment]
Hi,

Same problem here, I updated  R (4.2) , Bioconductor (3.15) and RcisTarget (1.16), still got the object 'indexCol' not found issue. I'm on Windows if that helps.

Thank you

**Comment by hk106609620** [comment]
> Hi,
> 
> Same problem here, I updated R (4.2) , Bioconductor (3.15) and RcisTarget (1.16), still got the object 'indexCol' not found issue. I'm on Windows if that helps.
> 
> Thank you

Have you solved this problem?   /(ㄒoㄒ)/~~

**Comment by BIOBRICK** [comment]
Yeah……I don't know why but the problem disappeared……
Maybe you should try to use souece file in version 1.2?(or even elder version……)



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年05月01日 19:31 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [aertslab/SCENIC] Error in runSCENIC_2_createRegulons: object 'indexCol' not found (Issue #290) |

Hi,

Same problem here, I updated R (4.2) , Bioconductor (3.15) and RcisTarget (1.16), still got the object 'indexCol' not found issue. I'm on Windows if that helps.

Thank you

Have you solved this problem? /(ㄒoㄒ)/~~

**Comment by hk106609620** [comment]
> Yeah……I don't know why but the problem disappeared…… Maybe you should try to use souece file in version 1.2?(or even elder version……)
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2022年05月01日 19:31 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.******@***.***> | | 主题 | Re: [aertslab/SCENIC] Error in runSCENIC_2_createRegulons: object 'indexCol' not found (Issue #290) | Hi, Same problem here, I updated R (4.2) , Bioconductor (3.15) and RcisTarget (1.16), still got the object 'indexCol' not found issue. I'm on Windows if that helps. Thank you Have you solved this problem? /(ㄒoㄒ)/~~ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

Oh mine /(ㄒoㄒ)/~~   i have tried all the previous versioins of scenic,,,,, it didn't work,,,,

**Comment by yixugalaxy** [comment]
> > Hi,
> > Same problem here, I updated R (4.2) , Bioconductor (3.15) and RcisTarget (1.16), still got the object 'indexCol' not found issue. I'm on Windows if that helps.
> > Thank you
> 
> Have you solved this problem? /(ㄒoㄒ)/~~

I installed an older version SCENIC 1.12 and it seems to fix my problem. Good luck!

**Comment by Hardy62442** [comment]
> > > Hi,
> > > Same problem here, I updated R (4.2) , Bioconductor (3.15) and RcisTarget (1.16), still got the object 'indexCol' not found issue. I'm on Windows if that helps.
> > > Thank you
> > 
> > 
> > Have you solved this problem? /(ㄒoㄒ)/~~
> 
> I installed an older version SCENIC 1.12 and it seems to fix my problem. Good luck!

Hi, maybe I met with a new problem. I have tried to install SCENIC 1.1.2 both by R and manually, and found that a new error: lazy loading failed for package 'SCENIC' occurs. Is your R or/and Bioconductor also correlates with the suggested plan A？ Thank you!

**Comment by s-aibar** [comment]
Hello @Hardy62442 @yixugalaxy @hk106609620 @BIOBRICK ,

Sorry! The error was due to a typo in the function in SCENIC!
I think it should now be solved. Please, re-install the package, sorry for the mess!

**Comment by Hardy62442** [comment]
> Hello @Hardy62442 @yixugalaxy @hk106609620 @BIOBRICK ,
> 
> Sorry! The error was due to a typo in the function in SCENIC! I think it should now be solved. Please, re-install the package, sorry for the mess!

Thank you! It has been solved now, and thank you for your effort!

**Comment by hk106609620** [comment]
> Hello @Hardy62442 @yixugalaxy @hk106609620 @BIOBRICK ,
> 
> Sorry! The error was due to a typo in the function in SCENIC! I think it should now be solved. Please, re-install the package, sorry for the mess!

Problem solved!  (●'◡'●)
