### ISSUE TITLE
RcisTarget row.names issue

### ISSUE THREAD

**Issue by jk86754** [aertslab/SCENIC#30]
Hi,

I am running into the following error message:

> runSCENIC_2_createRegulons(scenicOptions)
09:00	Step 2. Identifying regulons
tfModulesSummary:

 top5perTarget top10perTarget           w005          top50 top50perTarget 
           198            531            870            944           1254 
          w001 
          1323 
09:00	RcisTarget: Calculating AUC
Scoring database:  [Source file: mm9-500bp-upstream-7species.mc9nr.feather]
Scoring database:  [Source file: mm9-tss-centered-10kb-7species.mc9nr.feather]
10:02	RcisTarget: Adding motif annotation
Number of motifs in the initial enrichment: 2080070
Number of motifs annotated to the corresponding TF: 17945
10:09	RcisTarget: Prunning targets
[1] "error in running command"
Number of motifs that support the regulons: 17945
Error in `.rowNamesDF<-`(x, value = value) : 
  duplicate 'row.names' are not allowed
Calls: runSCENIC_2_createRegulons ... row.names<- -> row.names<-.data.frame -> .rowNamesDF<-
In addition: Warning message:
non-unique values when setting 'row.names': 

> sessionInfo()

R version 3.5.0 (2018-04-23)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux Server 7.2 (Maipo)

Matrix products: default
BLAS: /sc/wo/app/R/v3.5.0/lib64/R/lib/libRblas.so
LAPACK: /sc/wo/app/R/v3.5.0/lib64/R/lib/libRlapack.so

locale:
[1] LC_CTYPE=en_US.UTF-8 LC_NUMERIC=C
[3] LC_TIME=en_US.UTF-8 LC_COLLATE=en_US.UTF-8
[5] LC_MONETARY=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8
[7] LC_PAPER=en_US.UTF-8 LC_NAME=C
[9] LC_ADDRESS=C LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] parallel stats4 stats graphics grDevices utils datasets
[8] methods base

other attached packages:
[1] SingleCellExperiment_1.2.0 SummarizedExperiment_1.10.1
[3] DelayedArray_0.6.1 BiocParallel_1.14.1
[5] matrixStats_0.53.1 Biobase_2.40.0
[7] GenomicRanges_1.32.3 GenomeInfoDb_1.16.0
[9] IRanges_2.14.10 S4Vectors_0.18.3
[11] BiocGenerics_0.26.0 RColorBrewer_1.1-2
[13] foreach_1.4.4 AUCell_1.2.4
[15] RcisTarget_1.0.2 SCENIC_0.99.0-03

loaded via a namespace (and not attached):
[1] lattice_0.20-35 htmltools_0.3.6 blob_1.1.1
[4] XML_3.98-1.11 rlang_0.2.1 R.oo_1.22.0
[7] later_0.7.3 pillar_1.2.3 DBI_1.0.0
[10] R.utils_2.6.0 bit64_0.9-7 GenomeInfoDbData_1.1.0
[13] zlibbioc_1.26.0 R.methodsS3_1.7.1 codetools_0.2-15
[16] memoise_1.1.0 httpuv_1.4.4.1 AnnotationDbi_1.42.1
[19] GSEABase_1.42.0 Rcpp_0.12.17 xtable_1.8-2
[22] promises_1.0.1 feather_0.3.1 graph_1.58.0
[25] annotate_1.58.0 XVector_0.20.0 mime_0.5
[28] bit_1.1-14 hms_0.4.2 digest_0.6.15
[31] shiny_1.1.0 grid_3.5.0 tools_3.5.0
[34] bitops_1.0-6 magrittr_1.5 RCurl_1.95-4.10
[37] RSQLite_2.1.1 tibble_1.4.2 pkgconfig_2.0.1
[40] Matrix_1.2-14 data.table_1.11.4 iterators_1.0.9
[43] R6_2.2.2 compiler_3.5.0

Any help would be appreciated!

Joe

**Comment by jk86754** [comment]
I sent you an email.

**Comment by wurentian** [comment]
I am having a very similar issue. 
> runSCENIC_2_createRegulons(scenicOptions)
23:08	Step 2. Identifying regulons
tfModulesSummary:
 top5perTarget           w005 top10perTarget top50perTarget          top50           w001 
           161            226            281            882           1137           1220 
23:08	RcisTarget: Calculating AUC
Scoring database:  [Source file: hg19-500bp-upstream-7species.mc9nr.feather]
Scoring database:  [Source file: hg19-tss-centered-10kb-7species.mc9nr.feather]
00:54	RcisTarget: Adding motif annotation
Number of motifs in the initial enrichment: 1568977
Number of motifs annotated to the corresponding TF: 11013
01:01	RcisTarget: Prunning targets
Number of motifs that support the regulons: 11013
Error in `.rowNamesDF<-`(x, value = value) : 
  duplicate 'row.names' are not allowed
In addition: Warning messages:
1: In serialize(data, node$con, xdr = FALSE) :
  'package:stats' may not be available when loading
2: In serialize(data, node$con, xdr = FALSE) :
  'package:stats' may not be available when loading
3: In serialize(data, node$con, xdr = FALSE) :
  'package:stats' may not be available when loading
4: In serialize(data, node$con, xdr = FALSE) :
  'package:stats' may not be available when loading
5: In serialize(data, node$con, xdr = FALSE) :
  'package:stats' may not be available when loading
6: In serialize(data, node$con, xdr = FALSE) :
  'package:stats' may not be available when loading
7: In serialize(data, node$con, xdr = FALSE) :
  'package:stats' may not be available when loading
8: In serialize(data, node$con, xdr = FALSE) :
  'package:stats' may not be available when loading
9: non-unique values when setting 'row.names': ‘ABCF2__MATR3’, ‘ACO1__RGS5’, ‘ADNP__RGS5’, ‘AFF4__MATR3’, ‘AFF4__RGS5’, ‘AGGF1__RGS5’, ‘AHCTF1__MATR3’, ‘AKR1A1__MATR3’, ‘ALX1__MATR3’, ‘ANXA11__MATR3’, ‘ANXA11__RGS5’, ‘APEX1__MATR3’, ‘APEX1__RGS5’, ‘APEX2__RGS5’, ‘AR__RGS5’, ‘ARG2__RGS5’, ‘ARNT__RGS5’, ‘ARNT2__RGS5’, ‘ASCC1__RGS5’, ‘ASH2L__RGS5’, ‘ASPSCR1__MATR3’, ‘ASPSCR1__RGS5’, ‘ATF2__MATR3’, ‘ATF4__MATR3’, ‘ATF4__RGS5’, ‘ATF6B__MATR3’, ‘ATF6B__RGS5’, ‘ATF7__RGS5’, ‘ATOH8__RGS5’, ‘BAD__MATR3’, ‘BATF__MATR3’, ‘BATF__RGS5’, ‘BAX__MATR3’, ‘BAX__RGS5’, ‘BBX__MATR3’, ‘BBX__RGS5’, ‘BCLAF1__MATR3’, ‘BDP1__MATR3’, ‘BHLHE22__MATR3’, ‘BHLHE41__MATR3’, ‘BHLHE41__RGS5’, ‘BNC2__MATR3’, ‘BNC2__RGS5’, ‘BPTF__MATR3’, ‘BPTF__RGS5’, ‘BRF2__MATR3’, ‘CANX__MATR3’, ‘CANX__RGS5’, ‘CBX3__MATR3’, ‘CBX3__RGS5’, ‘ [... truncated] 



And when I do 
> motifEnrichment_selfMotifs_wGenes[order(motifEnrichment_selfMotifs_wGenes$NES,decreasing=TRUE),][1:5,(1:ncol(motifEnrichment_selfMotifs_wGenes)-1), with=F]
   motifDb    geneSet                   motif  NES   AUC highlightedTFs TFinDB                                       TF_highConf
1:    10kb E2F1_top50    transfac_pro__M00920 18.2 0.421           E2F1     ** E2F1; E2F3; E2F4; E2F7; TFDP1 (directAnnotation).
2:    10kb E2F1_top50    transfac_pro__M00918 18.0 0.417           E2F1     **       E2F1; E2F3; E2F4; TFDP1 (directAnnotation).
3:    10kb E2F1_top50 homer__TTCGCGCGAAAA_E2F 17.9 0.415           E2F1      *                                                  
4:    10kb E2F1_top50            cisbp__M3134 17.8 0.413           E2F1     **                          E2F1 (directAnnotation).
5:    10kb E2F1_top50    transfac_pro__M00939 17.8 0.412           E2F1     **       E2F1; E2F3; E2F4; TFDP1 (directAnnotation).
                                                                     TF_lowConf nEnrGenes rankAtMax
1:                                           E2F5 (inferredBy_MotifSimilarity).        19      1144
2:                          E2F2; E2F5; E2F7; RB1 (inferredBy_MotifSimilarity).        21      2732
3:                       E2F1; E2F4; TFDP1; TFDP2 (inferredBy_MotifSimilarity).        24      3805
4: E2F2; E2F3; E2F4; E2F5; E2F7; E2F8; RB1; TFDP1 (inferredBy_MotifSimilarity).        20      1044
5:                               E2F2; E2F5; E2F7 (inferredBy_MotifSimilarity).        22      2253


Is there anything I can do to fix it?
Thank you,
Rentian

**Comment by wurentian** [comment]
By going through the code, I think my issue is because GENIE3 generated the linkList with redundant TF and Target links. Manually remove the redundant row by !duplicated() first before define row names seems working.

**Comment by s-aibar** [comment]
Thank you! 
This is now checked both in GENIE3 & the function to create the coexpression network
