### ISSUE TITLE
Warning in .AUCell_calcAUC: Using only the first 14 genes (aucMaxRank) to calculate the AUC.

### ISSUE THREAD

**Issue by zhang-TD** [aertslab/SCENIC#302]
Hi,
    When I am using the function "runSCENIC_3_scoreCells". I met a warning: "Warning in .AUCell_calcAUC(geneSets = geneSets, rankings = rankings, nCores = nCores,  :   Using only the first 14 genes (aucMaxRank) to calculate the AUC."
    Is this warning important?  Will my results be unreliable because of this warning? Thank you very much!

**Comment by s-aibar** [comment]
Dear @zhang-TD ,

There is a bug in AUCell version `1.18.0`. The bug has now been corrected, so please install the latest version of the package (either 1.18.1, which will take a few hours/days to become available from Bioconductor, or `1.19.1` from the Github repository).

Sorry for the inconvenience!
