### ISSUE TITLE
Could you more Specify Example data format? 

### ISSUE THREAD

**Issue by kysbbubbu** [aertslab/SCENIC#31]
I want to do SCENIC analysis on my own expression set 
And I find difficulties in inputting my data.

Because, example files were not provided (CellLabels.tsv, expression.txt)
I could not figure out how to make those two files from expression_mRNA_17-Aug-2014.txt (example file)
Could you more Specify Example data format like below  image (from Granatum)? 

![image](https://user-images.githubusercontent.com/38550028/41953121-cc977144-7a0e-11e8-9f1d-85a833d7b95d.png)

**Comment by s-aibar** [comment]
Hello,

The [introduction and setup tutorial](https://htmlpreview.github.io/?https://github.com/aertslab/SCENIC/blob/master/inst/doc/SCENIC_Setup.html#sample-dataset-download-format) provides an example of how to download and format the input data (last section, "Sample dataset: Download & format": the expression matrix can be downloaded from GEO, and the cell info/metadata is included in package AUCell). It also explains the type of expression matrix expected (Section "[Input: expression matrix](https://htmlpreview.github.io/?https://github.com/aertslab/SCENIC/blob/master/inst/doc/SCENIC_Setup.html#input-expression-matrix)").

I'll add to the tutorial a preview of these objects. They should look like this (your data seems to be ok): 
```
> exprMatrix[1:5,1:4]
         1772071015_C02 1772071017_G12 1772071017_A05 1772071014_B06
Tspan12               0              0              0              3
Tshz1                 3              1              0              2
Fnbp1l                3              1              6              4
Adamts15              0              0              0              0
Cldn12                1              1              1              0
> head(cellLabels)
                   CellType
1772071015_C02 interneurons
1772071017_G12 interneurons
1772071017_A05 interneurons
1772071014_B06 interneurons
1772067065_H06 interneurons
1772071017_E02 interneurons
```

I think with this information should be enough...  If you can explain a bit more in detail what you think is missing, I would gladly add it to the tutorial.
