### ISSUE TITLE
Old SCENIC

### ISSUE THREAD

**Issue by juugii** [aertslab/SCENIC#33]
Dear Aerts team,

Thank you for your great job on SCENIC(s) and the regulon approach.

I have been using pySCENIC and R SCENIC/AUCell for a few months. You recently updated lots of your packages and their associated workflows and tutorials, completely removing the previous ones. There are many, many differences with the previous versions. I used to work with pySCENIC and switch to R-SCENIC/AUCells for analyses. I need to reproduce some old results, but I have to face some analysis issues. In order to understand the origin of the problems I would appreciate to build on the old tutorials you provided.

In order to maintain a compatibility with older workflows, could you please give access to these previous workflow/tutorials ?

eg.
https://raw.githubusercontent.com/aertslab/SCENIC/master/inst/doc/Step3.1_NwActivity.html
https://raw.githubusercontent.com/aertslab/SCENIC/master/inst/doc/Step3.2_BinaryNwActivity.html

Many thanks,
Best regards.

**Comment by s-aibar** [comment]
Dear juugii, 

Github keeps all the previous versions of the repositories. You can access them for example from the "commits" link at the top of the repository. From there, you can select the version/date you would like to see (e.g. last version of SCENIC before the updates in May/June: https://github.com/aertslab/SCENIC/tree/df3fb16b34a17a17b47d45485f4be86363ba834d). I think you should be able to access the old tutorials from there too... (Let me know if you don't...)

**Comment by juugii** [comment]
Dear s-aibar,

Thank you for your answer. I am aware of version tracking and the possibility to browse older version of repositories in github. However, as I explained, it is not possible for me to reach the old versions of the tutorials. Links to older tutorials from previous versions in the repository are pointing to missing information, eg.:

Error: Cannot load file https://raw.githubusercontent.com/aertslab/SCENIC/master/inst/doc/Step3.2_BinaryNwActivity.html

Best regards.

**Comment by YuxuanZheng94** [comment]
I have the same problem, and I need the older version SCENIC. However, I can't find that.
