### ISSUE TITLE
Error in t-SNE plots based on AUC scrore

### ISSUE THREAD

**Issue by lyc1234** [aertslab/SCENIC#34]
Hi,
Thanks for the great tutorial for applications of AUCell as well as the recently updated website providing a user-friendly interface for SCOPE! 

Based off on the packages your team has kindly provided, I am very interested in performing intra- and inter-species geneset analysis for my datasets. However, we have met with a small problem when trying to get the code to work as described below and would greatly appreciate any assistance and/or feedback:

We have been trying to graph t-SNE plots based on  the AUC score using the same dataset that was published on the AUCell website, more specifically, this line
“passThreshold <- getAUC(cells_AUC)[geneSetName,] >  selectedThresholds[geneSetName]
  if(sum(passThreshold) >0 )
  {
    aucSplit <- split(getAUC(cells_AUC)[geneSetName,], passThreshold)
    
    # Assign cell color
    cellColor <- c(setNames(colorPal_Neg[cut(aucSplit[[1]], breaks=nBreaks)], names(aucSplit[[1]])), 
    setNames(colorPal_Pos[cut(aucSplit[[2]], breaks=nBreaks)], names(aucSplit[[2]])))
    
    # Plot
    plot(cellsTsne, main=geneSetName,
    sub="Pink/red cells pass the threshold",
    col=cellColor[rownames(cellsTsne)], pch=16) 
  }”
Here, we ran into an error saying “Error in xy.coords(x,y,xlabel,ylabel,log):’x’ is a list, but does not have components ‘x’ and ‘y.’” Could I check if we are missing out on some lines of analyses? 

Thank you so much once again for your time!

**Comment by s-aibar** [comment]
Hello @lyc1234 ,

The you were probably trying to use the object returned by `Rtsne()` (which is indeed a list). If you use `cellsTsne$Y` it should work...

```
# cellsTsne <- Rtsne(t(logMatrix)) ; ...
names(cellsTsne)
cellsTsne <- cellsTsne$Y
plot(cellsTsne)
```
