### ISSUE TITLE
Memory usage while computing AUC

### ISSUE THREAD

**Issue by ZaZo0o** [aertslab/SCENIC#36]
Hi,

I am testing SCENIC on my single-cell data (563 cells, full length scRNAseq, RPKM data).
I am facing a problem of RAM usage while computing the AUC during the runSCENIC_2_createRegulons() step.
The cluster I use do not allow more than 250GB of RAM per node, and this step seems to use more that 250GB:

```
TERM_SWAP: job killed after reaching LSF swap usage limit.
Exited with signal termination: Killed.

Resource usage summary:

    CPU time :               879.38 sec.
    Max Memory :             255511.41 MB
    Average Memory :         76464.67 MB
    Total Requested Memory : 250000.00 MB
    Delta Memory :           -5511.41 MB
    (Delta: the difference between total requested memory and actual max usage.)
    Max Swap :               266461 MB

    Max Processes :          33
    Max Threads :            34
```

I am following the tutorial but with my own data, so I use the default settings (except that I use 30 cores).
I tried to run SCENIC with half of the cells and I get the same problem. I also tried to run SCENIC with only the genes that are differentially expressed between mu cell clusters (~5K genes) and same, I am facing the memory issue.

Is it normal that SCENIC uses so much RAM and Swap?

**Comment by s-aibar** [comment]
Hello,

The function `runSCENIC_2_createRegulons()` uses `BiocParallel::bplapply`. It seems that the default settings are not addequate on some systems, so you probably need to adjust the settings for BiocParallel. You can do some tests with this code:
```
library(BiocParallel)
registered() # your current settings
system.time(bplapply(1:1000, sqrt))

register(MulticoreParam(workers = 10), default = TRUE)
# or: register(SerialParam(), default = TRUE)
system.time(bplapply(1:1000, sqrt))
```

Plesase, let me know whether this helps,
Sara

**Comment by ZaZo0o** [comment]
Hello Sara,

thanks for the tip, I will test this asap and let you know if it works.

Isabelle

**Comment by marcovito** [comment]
Hi Isabelle,

I had the same problem. The only way I managed to solve it was lowering the nCores parameter.
Hope it helps,
Marco

**Comment by ZaZo0o** [comment]
Hi Marco,

I have found a thread (I don't remember where exactly) saying that the memory is not shared between cores but duplicated, so I did the same as you, I reduced the number of cores until it run (6 cores for me). It is of course longer to run but went well until step 3 where I got a new error, but related to data format, not to memory usage anymore.
```
Error in (function (classes, fdef, mtable)  :
  unable to find an inherited method for function 'AUCell_buildRankings' for signature '"data.frame"'
```

So I guess this problem is solved nd this message will be usefull for others.

Cheers,

Isabelle

**Comment by ZaZo0o** [comment]
Update:

When I succeeded to run SCENIC, I used a subset of genes (genes that are DE between the cell clusters, so ~5k genes).
Now I try to run SCENIC on the whole transcriptome (16k genes) and this time I am facing a SWAP memory issue (1Tb of SWAP!) after 5 hours of computing the step "RcisTarget: Prunning targets".
It does not change if I use 4, 6 or 10 cores.

I start to be a bit frustrated....

**Comment by deveale** [comment]
Hi Isabelle (or anyone else who might have run into the same issue), 

I had the memory issue which led me here (it was resolved by changing nCores as described here, thanks!), but then ran into the issue posted above:

Error in (function (classes, fdef, mtable)  :
  unable to find an inherited method for function 'AUCell_buildRankings' for signature '"data.frame"'

How did you resolve this? Thanks in advance! Brian

**Comment by s-aibar** [comment]
Dear @deveale ,

Indeed there is no "AUCell_buildRankings" for data.frame, the expression matrix is supposed to be either a matrix, dgCMatrix, ExpressionSet, or SummarizedExperiment.  e.g.: 
```
methods("AUCell_buildRankings")
```

You can just convert the data.frame to matrix with `as.matrix` (but make sure the conversion is done correctly... (e.g. careful with "factors")...

I have now added a check to the function that will show a message explaining this...

**Comment by mellyS** [comment]
> Update:
> 
> When I succeeded to run SCENIC, I used a subset of genes (genes that are DE between the cell clusters, so ~5k genes).
> Now I try to run SCENIC on the whole transcriptome (16k genes) and this time I am facing a SWAP memory issue (1Tb of SWAP!) after 5 hours of computing the step "RcisTarget: Prunning targets".
> It does not change if I use 4, 6 or 10 cores.
> 
> I start to be a bit frustrated....

Hi there :)
I could go until the last step by setting the number of cores to 1 and setting the threshold at 0.005 in the ScenicOption Settings. 
I hope it may help !
