### ISSUE TITLE
runSCENIC_3_scoreCells.R Line84 non-numeric error

### ISSUE THREAD

**Issue by wang-research** [aertslab/SCENIC#38]
Hi,

I found line 83-84 of runSCENIC_3_scoreCells.R:
```
trhAssignment <- getThresholdSelected(cells_AUCellThresholds)
trhAssignment <- signif(trhAssignment,3)
```
The 83-line gave a 'list' result, but 'signif' needs a numeric input? 
By the way, there are some 'NA' names in 'cells_AUCellThresholds'. Coud I simply delete theme items?

Thank you, sincerely.

**Comment by jaimicore** [comment]
Hi

I had the same problem but I fixed it with the following change:

```
## Original line:
trhAssignment <- signif(trhAssignment,3)
```

```
Changes:
trhAssignment <- as.list(signif(unlist(trhAssignment), 3))
```

You should pass the argument as a vector, in order to apply the *signif* function, then you can convert the resulting vector in a list.

**Comment by wang-research** [comment]
Thanks! I fixed it.

**Comment by jaimicore** [comment]
I modified the code in runSCENIC_3_scoreCells.R

After that, in R:

`
detach("package:SCENIC", unload = TRUE);
remove.packages("SCENIC")
`

Then compress the file and compile it from the command line:
`
R CMD INSTALL SCENIC.tar.gz
`

**Comment by afaissa** [comment]
> Hi,
> 
> I had a same issue.
> My question is how you fixed the problem in detail.
> Did you change the line from runSCENIC_3_scoreCells.R file? and re-install the whole package?
> or you newly define runSCENIC_3_scoreCells function only in R and used it?
> I am trying either way but, none of them are working properly.
> 
> if you can describe more in detail, it would be very helpful.

Hi, 

Did you figure out this issue? I have the same problem as you. Can you help me?

**Comment by rach226a** [comment]
Hi,

I believe the issue is related to parallelization within the AUCell_exploreThresholds() function (of runSCENIC_3_scoreCells). It seems like some of the cores are outputting NA. If you run AUCell_exploreThresholds() many times, different regulons will be replaced by NA value each time. It seems to work if you lower your nCores or set nCores = 1 (safest option!). I hope this helps anyone who runs into this issue!
