### ISSUE TITLE
Can't load RcisTarget databases 

### ISSUE THREAD

**Issue by HuynhLab** [aertslab/SCENIC#43]
Dear SCENIC team, 

I'm following the tutorial for SCENIC and ran into this problem: 

library(SCENIC)
dbFiles <- c("https://resources.aertslab.org/cistarget/databases/homo_sapiens/hg38/refseq_r80/mc9nr/gene_based/hg38__refseq-r80__500bp_up_and_100bp_down_tss.mc9nr.feather","https://resources.aertslab.org/cistarget/databases/homo_sapiens/hg38/refseq_r80/mc9nr/gene_based/hg38__refseq-r80__10kb_up_and_down_tss.mc9nr.feather")
for(featherURL in dbFiles){
  download.file(featherURL, destfile=basename(featherURL))
  descrURL <- gsub(".feather$", ".descr", featherURL)
  if(file.exists(descrURL)) download.file(descrURL, destfile=basename(descrURL))
}
org="hgnc"
dbDir="/path/Rscenic"
myDatasetTitle="SCENIC"

scenicOoptions <- initializeScenic(org=org, datasetTitle = myDatasetTitle, dbDir=dbDir)

ERROR MESSAGE: 
RcisTarget databases not found. Please, initialize them manually.

Am I missing anything? Both the *.feather files are located in /path/Rcenic 

Thank you for your help! 

Best, 
Gwen

**Comment by HuynhLab** [comment]
I just checked the file download integrity with sha256sum. The files were downloaded correctly. Oddly enough, everything loads fine with the hg19 links but not with hg38. Do you have any ideas why this is happening? 
$ sha256sum *
fea7f9159645392970ecb2c902fb0622681dd63b9a47b36363f50569c5989f62  hg38__refseq-r80__10kb_up_and_down_tss.mc9nr.feather
e7f980ec2f9ddedcfc563d9ab045ea6b769eba654d3348a1fc6140b1575f9428  hg38__refseq-r80__500bp_up_and_100bp_down_tss.mc9nr.feather

## In R for hg19: 
> dbFiles <- c("https://resources.aertslab.org/cistarget/databases/homo_sapiens/hg19/refseq_r45/mc9nr/gene_based/hg19-500bp-upstream-7species.mc9nr.feather",
"https://resources.aertslab.org/cistarget/databases/homo_sapiens/hg19/refseq_r45/mc9nr/gene_based/hg19-tss-centered-10kb-7species.mc9nr.feather")
> dir.create("cisTargetdb"); setwd("cisTargetdb")
> for(featherURL in dbFiles)
{
  download.file(featherURL, destfile=basename(featherURL)) # saved in current dir
  descrURL <- gsub(".feather$", ".descr", featherURL)
  if(file.exists(descrURL)) download.file(descrURL, destfile=basename(descrURL))
}
> library(SCENIC)
> library(AUCell)
> library(RcisTarget)
> org="hgnc"
> dbDir="cisTargetdb"
> myDatasetTitle="SCENIC Fetal"
> scenicOoptions <- initializeScenic(org=org, dbDir=dbDir, datasetTitle = myDatasetTitle, nCores=20)
# Motif databases selected: hg19-500bp-upstream-7species.mc9nr.feather, hg19-tss-centered-10kb-7species.mc9nr.feather

**Comment by jaimicore** [comment]
I had a similar warning. 

the issue came from the current directory where I was.

This is how I do in my code and is working:


```
dbFiles <- c("https://resources.aertslab.org/cistarget/databases/homo_sapiens/hg19/refseq_r45/mc9nr/gene_based/hg19-500bp-upstream-7species.mc9nr.feather",
             "https://resources.aertslab.org/cistarget/databases/homo_sapiens/hg19/refseq_r45/mc9nr/gene_based/hg19-tss-centered-10kb-7species.mc9nr.feather")
## mc9nr: Motif collection version 9: 24k motifs

## File names after download
downloadedDBFiles <- c("cisTarget_databases/hg19-500bp-upstream-7species.mc9nr.feather",
                       "cisTarget_databases/hg19-tss-centered-10kb-7species.mc9nr.feather")


## The databases are downloaded only in the case when the files do not exist.
if( !(file.exists(downloadedDBFiles[1]) & file.exists(downloadedDBFiles[2])) ){
  
  ## Create and move to the new folder
  dir.create("cisTarget_databases");
  setwd("cisTarget_databases") 
  for(featherURL in dbFiles)
  {
    download.file(featherURL, destfile=basename(featherURL)) # saved in current dir
    descrURL <- gsub(".feather$", ".descr", featherURL)
    if(file.exists(descrURL)) download.file(descrURL, destfile=basename(descrURL))
  }
  setwd("..")
  
}

## ...

system("ln -s /absolute/path/cisTarget_databases databases")


## Config object
org="hgnc" ## Set to Homo sapiens
dbDir="databases" # RcisTarget databases location
myDatasetTitle="SCENIC example on Mouse brain" # choose a name for your analysis
scenicOptions <- initializeScenic(org = org,
                                  dbDir = dbDir,
                                  datasetTitle = myDatasetTitle,
                                  nCores = nb.cores)
```

I used the absolute path to the databases folder.

**Comment by wisooshin** [comment]
Hi there,

I had the same issue and I got around this by downloading the 10species file and changing the name of this .feather file to 7species. Simply change the 10 in the "mm9-500bp-upstream-10species.mc9nr.feather" to 7: "mm9-500bp-upstream-7species.mc9nr.feather". Although I was using the mouse genome, maybe the issue is the same with the human genome. 

It seemed like no matter how I downloaded the file, through R code, through the website, through zsync_curl, the 7 species file was always corrupt.

Seems to be working great now!

Hope this helps

**Comment by SamAllon** [comment]
I experienced a similar issue as the opening post: the mm10 database leads to the "RcisTarget databases not found," but the mm9 database is successful at the initializeScenic step.

**Comment by ccasar** [comment]
The problem here is that the `initializeScenic` function checks for the DB names listed by the `defaultDbNames` object only.

So you have to, as the given warning says, set the paths yourself, e.g.:

```
scenic_opts <- initializeScenic(org='hgnc',
                                datasetTitle='Analysis title', 
                                nCores=10) 
hg38_dbs <- list('500bp'= 'hg38__refseq-r80__500bp_up_and_100bp_down_tss.mc9nr.feather', 
                 '10kb' = 'hg38__refseq-r80__10kb_up_and_down_tss.mc9nr.feather')
db_mcVersion <- 'v9'
db_path <- 'path/to/dbfiles'

scenic_opts@settings$dbs <- hg38_dbs
scenic_opts@settings$dbDir <- db_path
scenic_opts@settings$db_mcVersion <- db_mcVersion
```

**Comment by HuynhLab** [comment]
Thank you @ccasar for clarifying. What you suggested worked now.

**Comment by ccshao** [comment]
Hello, the database website could not be accessed again. `https://resources.aertslab.org/cistarget/help.html`

Also `https://bokeh.aertslab.org/cistarget/databases/` doesn't work.

**Comment by ghuls** [comment]
Use https://resources-mirror.aertslab.org/cistarget/help.html for now.
The main backend file server has problems which hopefully will be fixed for good soon.

**Comment by ccshao** [comment]
Thanks for the quick help!

**Comment by eegk** [comment]
I tried all solutions above and still have the same problem. Any idea?

**Comment by xqs-time** [comment]
Dear SCENIC team,

I'm following the tutorial for SCENIC and ran into this problem:

`library(RcisTarget)
a = importRankings("hg19-tss-centered-10kb-7species.mc9nr.feather")

Error in dbDescr["nColsAvailable", ] <- nColsInDB : Change the parameter length to zero`

The data is correct，but it can not load the data by using the function. 
Thank you for your help!

**Comment by AAA-3** [comment]
> I had a similar warning.
> 
> the issue came from the current directory where I was.
> 
> This is how I do in my code and is working:
> 
> ```
> dbFiles <- c("https://resources.aertslab.org/cistarget/databases/homo_sapiens/hg19/refseq_r45/mc9nr/gene_based/hg19-500bp-upstream-7species.mc9nr.feather",
>              "https://resources.aertslab.org/cistarget/databases/homo_sapiens/hg19/refseq_r45/mc9nr/gene_based/hg19-tss-centered-10kb-7species.mc9nr.feather")
> ## mc9nr: Motif collection version 9: 24k motifs
> 
> ## File names after download
> downloadedDBFiles <- c("cisTarget_databases/hg19-500bp-upstream-7species.mc9nr.feather",
>                        "cisTarget_databases/hg19-tss-centered-10kb-7species.mc9nr.feather")
> 
> 
> ## The databases are downloaded only in the case when the files do not exist.
> if( !(file.exists(downloadedDBFiles[1]) & file.exists(downloadedDBFiles[2])) ){
>   
>   ## Create and move to the new folder
>   dir.create("cisTarget_databases");
>   setwd("cisTarget_databases") 
>   for(featherURL in dbFiles)
>   {
>     download.file(featherURL, destfile=basename(featherURL)) # saved in current dir
>     descrURL <- gsub(".feather$", ".descr", featherURL)
>     if(file.exists(descrURL)) download.file(descrURL, destfile=basename(descrURL))
>   }
>   setwd("..")
>   
> }
> 
> ## ...
> 
> system("ln -s /absolute/path/cisTarget_databases databases")
> 
> 
> ## Config object
> org="hgnc" ## Set to Homo sapiens
> dbDir="databases" # RcisTarget databases location
> myDatasetTitle="SCENIC example on Mouse brain" # choose a name for your analysis
> scenicOptions <- initializeScenic(org = org,
>                                   dbDir = dbDir,
>                                   datasetTitle = myDatasetTitle,
>                                   nCores = nb.cores)
> ```
> 
> I used the absolute path to the databases folder.

I tried that but kept getting this error:

```
Error in download.file(featherURL, destfile = basename(featherURL)) : 
  download from 'https://resources.aertslab.org/cistarget/databases/mus_musculus/mm9/refseq_r45/mc9nr/gene_based/mm9-500bp-upstream-7species.mc9nr.feather' failed
In addition: Warning messages:
1: In download.file(featherURL, destfile = basename(featherURL)) :
  downloaded length 392750781 != reported length 1081248976
2: In download.file(featherURL, destfile = basename(featherURL)) :
  URL 'https://resources.aertslab.org/cistarget/databases/mus_musculus/mm9/refseq_r45/mc9nr/gene_based/mm9-500bp-upstream-7species.mc9nr.feather': Timeout of 60 seconds was reached
```
