### ISSUE TITLE
error in plot_eRegulon function for downstream analysis

### ISSUE THREAD

**Issue by alirosen** [aertslab/SCENIC#431]
Hi guys! 

I am just trying to visualize my eRegulon activity for my scplus_obj with your plot_eRegulon function but am getting this error: 

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/gpfs/data/aifantislab/home/ar8089/PTCL_project/scenicplus/src/scenicplus/dimensionality_reduction.py", line 938, in plot_eRegulon
    gene_data = gene_data.sort_values()
  File "/gpfs/home/ar8089/.conda/envs/scenicplus/lib/python3.8/site-packages/pandas/util/_decorators.py", line 317, in wrapper
    return func(*args, **kwargs)
TypeError: sort_values() missing 1 required positional argument: 'by'
```

It seems like it's pointing to this chunk in the dim reduction script: 
# Gene data
if num_columns > 1:
    plt.subplot(num_rows, num_columns, i)
    i = i + 1
if 'Gene_based' in signature_keys:
    gene_data = data_mat[gene_based_name].squeeze()
 **gene_data = gene_data.sort_values()**
    embedding_plot = embedding.loc[gene_data.index.tolist()]
    o = np.argsort(gene_data)
                
Can anyone help me with this error? Thanks in advance!

**Comment by LMBei3353** [comment]
Hello, I encountered the same error as you. Could you please advise on how to handle it?
