### ISSUE TITLE
Can we 'plotTsne' with our own tsne data

### ISSUE THREAD

**Issue by WeiCSong** [aertslab/SCENIC#44]
Hi all, after i accomplished GRN(regulon scoring), i wish to plot GRN scores on t-sne plot obtained from Seurat package. But in the tutorial

[https://htmlpreview.github.io/?https://github.com/aertslab/SCENIC/blob/master/inst/doc/SCENIC_Running.html#optional-creatingcomparing-t-snes](url)

i found that 'plotTsne_compareSettings' function seems to plot based on tsne results calculated by Scenic package itself. I cant find where Scenic store tsne data(in Seurat, it is stored in object@dr$tsne@cell.embeddings)
Can anyone find out how to plot with 'GRN from Scenic' + 'tsne from Seurat'? Thanks all!

**Comment by sunwu93** [comment]
Hi goubegou,

An east way I do this is to import the AUC values generated from SCENIC into your seurat object as metadata. This information is stored at "int/3.4_regulonAUC.Rds". You can then use the featureplot function with your specific dimensional reduction you want to use at seurat@dr to look at TFs of interest. Heres the code;

`
library(SCENIC)
library(Seurat)

seurat_10X <- readRDS("seurat_object.Rds")
regulonAUC <- readRDS("int/3.4_regulonAUC.Rds")

temp_cells_AUC_matrix <- 
  t(as.data.frame(getAUC(regulonAUC)))

temp_cells_AUC_matrix_sorted <- 
  temp_cells_AUC_matrix[rownames(seurat_10X@meta.data),,drop=FALSE]

temp_cells_AUC_matrix_sorted <- 
  as.data.frame.matrix(temp_cells_AUC_matrix_sorted)

seurat_10X <- AddMetaData(seurat_10X, 
                          metadata = temp_cells_AUC_matrix_sorted)

FeaturePlot(
    seurat_10X,
    features.plot = "TF_name",
    pt.size = 2,
    cols.use = c("light blue", "red3"), 
    no.axes = T, 
    reduction.use = "UMAP20"
  )

`
Hope that helps.
Sunny

**Comment by goubegou** [comment]
> Hi goubegou,
> 
> An east way I do this is to import the AUC values generated from SCENIC into your seurat object as metadata. This information is stored at "int/3.4_regulonAUC.Rds". You can then use the featureplot function with your specific dimensional reduction you want to use at seurat@dr to look at TFs of interest. Heres the code;
> 
> 'library(SCENIC)
> library(Seurat)
> 
> seurat_10X <- readRDS("seurat_object.Rds")
> regulonAUC <- readRDS("int/3.4_regulonAUC.Rds")
> 
> temp_cells_AUC_matrix <-
> t(as.data.frame(getAUC(regulonAUC)))
> 
> temp_cells_AUC_matrix_sorted <-
> temp_cells_AUC_matrix[rownames([seurat_10X@meta.data](mailto:seurat_10X@meta.data)),,drop=FALSE]
> 
> temp_cells_AUC_matrix_sorted <-
> as.data.frame.matrix(temp_cells_AUC_matrix_sorted)
> 
> seurat_10X <- AddMetaData(seurat_10X,
> metadata = temp_cells_AUC_matrix_sorted)
> 
> FeaturePlot(
> seurat_10X,
> features.plot = "TF_name",
> pt.size = 2,
> cols.use = c("light blue", "red3"),
> no.axes = T,
> reduction.use = "UMAP20"
> )`
> 
> Hope that helps.
> Sunny

Great,Thank you!
