### ISSUE TITLE
Bioconductor version 

### ISSUE THREAD

**Issue by flde** [aertslab/SCENIC#459]
Hey Scenic-Team, 

Many thanks for the package. To install the latest scenic version in R you require bioconductor version 4.0 according to the SCENIC_Setup.html. However, that version of bioconductor does not exist, right? Highest is 3.19.  

Best, Florian

**Comment by ghuls** [comment]
Try to use pySCENIC instead of SCENIC (deprecated).

Container versions are available:
https://pyscenic.readthedocs.io/en/latest/installation.html#docker-podman-and-singularity-apptainer-images

**Comment by flde** [comment]
Many thanks for the great package, the pySCENIC version works very nicely.
