### ISSUE TITLE
runSCENIC_3_scoreCells error

### ISSUE THREAD

**Issue by campsj** [aertslab/SCENIC#48]
I get this error when I want to run the third function in the SCENIC wrapper
```
library(SCENIC)
scenicOptions <- readRDS("int/scenicOptions.Rds")
scenicOptions@settings$verbose <- TRUE
scenicOptions@settings$nCores <- 20
scenicOptions@settings$seed <- 123

runSCENIC_1_coexNetwork2modules(scenicOptions)
runSCENIC_2_createRegulons(scenicOptions)
runSCENIC_3_scoreCells(scenicOptions, exprMat)
```

```
13:58	Creating TF modules
             [,1]
nTFs         1006
nTargets    10418
nGeneSets    6036
nLinks    4169753

 top5perTarget          top50 top10perTarget top50perTarget           w001           w005 
           415            529            826           1006           1006           1006 
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
    2.0     8.0    24.0   159.8   106.0  3396.0 
    min      1%      5%     10%     50%    100% 
2322.00 2373.64 2777.20 2954.80 3546.00 5308.00 

Error in gzfile(file, "rb") : cannot open the connection
```

**Comment by campsj** [comment]
After checking further I found that the perplexity is too high. It prints this error message: 
`"Couldn't create tSNE for: AUC, 50PCs, 50perpl. Error msg:Error in Rtsne.default(tsneMat, initial_dims = as.integer(initial_dims), : Perplexity is too large.\n"`

I saw that perplexity is defined in the initializeSCENIC function but is there also an easier way to change perplexity?

**Comment by sunminxuan** [comment]
Hey Jordi, I also got the same errors, did you fix it?

**Comment by campsj** [comment]
The error is only linked to the tSNE plotting of the scoreCells wrapper, so you can just go on. In initializeScenic there is a standard perplexity of 50 that is not changeable to my knowledge. You can just resume and put the perplexity that you prefer further on.

**Comment by sunminxuan** [comment]
ThankS, Jordi!

**Comment by sunminxuan** [comment]
if you want to change the perplexity, here is the code:
scenicOptions@settings$defaultTsne$perpl <- _yourDesiredValue_
