### ISSUE TITLE
runSCENIC_3_scoreCells cut.default error

### ISSUE THREAD

**Issue by SamAllon** [aertslab/SCENIC#49]
Breaks-related error during runSCENIC_3_scoreCells:

````
> runSCENIC_3_scoreCells(scenicOptions, exprMat)
14:21   Step 3. Analyzing the network activity in each individual cell

Number of regulons to evaluate on cells: 336
Biggest (non-extended) regulons:
         Taf1 (2113g)
         Elf1 (2069g)
         Fli1 (1707g)
         Elf4 (1511g)
         Elk3 (1287g)
         Ep300 (1147g)
         Gabpa (1043g)
         Elk4 (993g)
         Elk1 (971g)
         Etv6 (623g)
Quantiles for the number of genes detected by cell:
(Non-detected genes are shuffled at the end of the ranking. Keep it in mind when choosing the threshold for calculating the AUC).
   min     1%     5%    10%    50%   100%
1556.0 1636.8 1782.0 1910.0 2386.0 7637.0
Using 20 cores.
Using 20 cores.
Error in cut.default(a, breaks = 100) : 'breaks' are not unique
```
`

**Comment by s-aibar** [comment]
Dear @SamAllon ,

Thank you for the report. I have added some checks to try to find why is it happening. To find it more easily it could help if you can tell us which is the last file that was generated (e.g. in folder "int" and/or "output") and whether you are providing any metadata (e.g. "cellInfo") to plot in the tSNEs.

**Comment by chent5** [comment]
Hi,

Thanks a lot for developing this package. I have exactly the same error...
<img width="915" alt="image" src="https://user-images.githubusercontent.com/40006284/52535518-73b42c80-2d1d-11e9-8210-51a9557be199.png">

Here are the files and corresponding time they were generated in the int folder:
<img width="1000" alt="image" src="https://user-images.githubusercontent.com/40006284/52535757-33a27900-2d20-11e9-9203-c3fece5a133a.png">

Here are the files in the output folder:
<img width="976" alt="image" src="https://user-images.githubusercontent.com/40006284/52535560-dd343b00-2d1d-11e9-9658-eb59e2c458fb.png">

I saved a Seurat object @meta.data into cellInfo.Rds, including nGene, nUMI, group assignment, clustering results.

Hope these would help and this problem could be solved soon. Please let me know if you need any other information.

Thank you so much!

**Comment by chent5** [comment]
I have figured out what's wrong with my code. I should not put the whole SeuratObject@meta.data into cellinfo.Rds. When I only save the clustering results into cellinfo.Rds as a single column of dataframe, the error message is gone.

**Comment by Sijin-ZhangLab** [comment]
Hi,  when I run "runSCENIC_3_scoreCells(scenicOptions, exprMat_log,skipHeatmap = TRUE)", I got an error:

Error in .AUCell_calcAUC(geneSets = geneSets, rankings = rankings, nCores = nCores,  :
  Valid 'mctype': 'snow' or 'doMC'

Could you help me?
