### ISSUE TITLE
error in runSCENIC_3_scoreCells

### ISSUE THREAD

**Issue by MichaelPeibo** [aertslab/SCENIC#50]
Hi, SCENIC team
I got an error when I run `runSCENIC_3_scoreCells`

> 
> Error in signif(trhAssignment, 3):
>     non-numeric argument to mathematical function

Any suggestion that where error comes from?
Thanks!

PLUS: I saw some different errors about` runSCENIC_ ` functions, is it possible due to OS environment?
I am using 

> Linux version 2.6.32-696.13.2.el6.x86_64 (mockbuild@c1bl.rdu2.centos.org) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-18) (GCC) ) #1 SMP Thu Oct 5 21:22:16 UTC 2017

**Comment by MichaelPeibo** [comment]
I figured this out by searching `signif` in this repository, there is similar closed issue [reporting this error](https://github.com/aertslab/SCENIC/issues/38).
I do not know why it has this error...

**Comment by liuyifang** [comment]
solved by reducing nCores from 16 to 8

**Comment by SonglingZhang** [comment]
I also encountered this error，Reducing ncore from 8 to 4 solved this error。
