### ISSUE TITLE
importGRNBoostResults() - help

### ISSUE THREAD

**Issue by ltosti** [aertslab/SCENIC#58]
Dear all,

It would be really useful to have this function implemented as to import the arboreto output back in R. Is there any progress in the implementation of this function? 
Are you able to provide a workaround in the meantime to perform this step?

Thank you!

**Comment by s-aibar** [comment]
A similar function is now implemented:  `importArboreto` (loads the linkList, but you might need to check the thresholds to create the co-expression modules)
