### ISSUE TITLE
New release of SCIENIC

### ISSUE THREAD

**Issue by ati-lz** [aertslab/SCENIC#6]
Hi,

I have problems installing the packages, some links are not working, and when I install them from bioconductor, installing SCENIC from devtools gives an error about incompatibility of the versions (about AUCell I think since SCENIC needs .99 version while from bioconductor we have 1.0.... Also when I install from the link you provided the 0.99 version, I still get an error about it while installing SCENIC...). Also not sure if I can find RcisTarget in Bioconductor yet...
You have mentioned that 31st of October all required packages will be available in Bioconductor, and early November SCENIC will be updated to work with bioconductor versions...
I think it has not happened yet!
Can you give a date about the new release which wont have problems with different versions of required packages?

Many thanks!
Ati

**Comment by s-aibar** [comment]
Hello,

Sorry, the inclusion of RcisTarget in Bioconductor was finally delayed to the next release, so the update of SCENIC to make it consistent with newer/Bioconductor versions has been postponed (hopefully not more that a few more weeks).

Meanwhile, make sure that you use the versions mentioned in the [Readme](https://github.com/aertslab/SCENIC/blob/master/README.md):

```
# GENIE3:
install.packages("https://bioconductor.org/packages/devel/bioc/src/contrib/GENIE3_0.99.7.tar.gz", repos=NULL)
# AUCell:
install.packages("http://scenic.aertslab.org/downloads/Rpackages/AUCell_0.99.5.tar.gz", repos=NULL)
# RcisTarget:
install.packages("http://scenic.aertslab.org/downloads/Rpackages/RcisTarget_0.99.0.tar.gz", repos=NULL)
 
# Human: install.packages("http://scenic.aertslab.org/downloads/databases/RcisTarget.hg19.motifDatabases.20k_0.1.1.tar.gz", repos=NULL)
# Mouse: install.packages("http://scenic.aertslab.org/downloads/databases/RcisTarget.mm9.motifDatabases.20k_0.1.1.tar.gz", repos=NULL)
```

**Comment by ati-lz** [comment]
Hi,

Thanks for the reply, but there are two issues even for now:

First, installing these packages from the links provided in Readme not works for all of them (For GENIE3, The URL seems not working, so I install GENIE3 from bioconductor).
But the AUCell V 0.99.5 and RcisTarget V 0.99.0 are installable via this links...

But the main problem, is after installing these packages from these links (except for GENIE3), when installing SCENIC from devtools with this command:

# SCENIC:
devtools::install_github("aertslab/SCENIC")

it seems that it reinstalls the GENIE3 and AUCell!! and for AUcell we need the version 0.99.5 while the SCIENIC automatically updates it AUCell_1.0.0. and then it complains that it needs the older version, so the installation of SCENIC fails!

Would really help if you can provide a solution! Thansk!

Ati
