### ISSUE TITLE
Question about databases

### ISSUE THREAD

**Issue by YandongZheng** [aertslab/SCENIC#61]
Hi:
  Thank you for developing such a good tool and I  am following tutorials to learn SCENIC.
  Now,I have a question about databases: I find there are two types  of databases,one is ".fether",the other is".RData".
   When I used "mm9-tss-centered-10kb-10species.mc9nr.feather" 
`library(SCENIC)
org="mgi" # or hgnc, or dmel
dbDir="databases" # RcisTarget databases location
myDatasetTitle="SCENIC example on Mouse brain" # choose a name for your analysis
scenicOptions <- initializeScenic(org=org, dbDir=dbDir, datasetTitle=myDatasetTitle, nCores=20) 
Warning message: 
"RcisTarget databases not found. Please, initialize them `manually."`
`genesKept <- geneFiltering(exprMat, scenicOptions=scenicOptions,
+                            minCountsPerGene=3*.01*ncol(exprMat),
+                            minSamples=ncol(exprMat)*.01)   
Error is "Error in getDatabases(scenicOptions)[[1]] : Subscript out "`

  When I used "mm9_10kbpAroundTss_motifRanking.RData"
  In the step "initializeScenic" ,the Warning message did not occur , but  after "geneFiltering" the Error "Subscript out " also occured .

  Thank you in advance for your time !

Best wishes!

**Comment by YandongZheng** [comment]
Hi:
  Thank you for developing such a good tool and I am following tutorials to learn SCENIC.
  Now,I have a question about databases: I find there are two types of databases,one is ".fether",the other is".RData".

  When I used "mm9-tss-centered-10kb-10species.mc9nr.feather"
  `library(SCENIC)`
  `org="mgi"` # or hgnc, or dmel 
  `dbDir="databases"` # RcisTarget databases location 
  `myDatasetTitle="SCENIC example on Mouse brain"` # choose a name for your analysis 
  `scenicOptions <- initializeScenic(org=org, dbDir=dbDir, datasetTitle=myDatasetTitle,nCores=20)`      
  `Warning message: "RcisTarget databases not found. Please, initialize them manually."`
  `genesKept <- geneFiltering(exprMat, scenicOptions=scenicOptions,
minCountsPerGene=3*.01*ncol(exprMat), minSamples=ncol(exprMat)*.01) `  
  `Error is "Error in getDatabases(scenicOptions)[[1]] : Subscript out "`

  When I used "mm9_10kbpAroundTss_motifRanking.RData"
  In the step "initializeScenic" ,the Warning message did not occur , but after "geneFiltering" the Error "Subscript out " also occured .

  Thank you in advance for your time !

  Best wishes!

**Comment by s-aibar** [comment]
Dear @YandongZheng ,

It seems that the functions don't find the `.feather` databases. 

Have you downloaded them (https://rawcdn.githack.com/aertslab/SCENIC/master/inst/doc/SCENIC_Setup.html#species-specific-databases) and indicated the path in which they are found? `getDatabases(scenicOptions)` 

They need to be indicated with:
```
org="mgi"
data(defaultDbNames)
dbs <- defaultDbNames[[org]]
scenicOptions <- initializeScenic(org=org, dbDir="databases", dbs=dbs, 
datasetTitle="whatever...", nCores=5) 
```


You can also try with this (new) function, to see what might be the problem: 

```
dbLoadingAttempt <- function(dbFilePath){
  ret <- FALSE
  ret <- tryCatch({
    md <- feather::feather_metadata(dbFilePath)
    md$path
    md$dim[2] == length(md$types)
    randomCol <- sample(names(md$types),1)
    rnk <- importRankings(dbFilePath, randomCol)
    TRUE
  }
  , error=function(e){
    print(e$message)
    return(FALSE)
  }
  )

  return(ret)
}
```

```
dbLoadingAttempt("databases/mm9-500bp-upstream-7species.mc9nr.feather")
```

**Comment by xulahong** [comment]
Hi, 
I am working on Arabidopsis. There is no cisTarget database for Arabidopsis. Could you please add it?

Thanks!

**Comment by saisaitian** [comment]
Hello， I have a problem. Could you tell me how to solve it?
When I runing the following code, it always get error.
![image](https://user-images.githubusercontent.com/26356557/110061977-70c48280-7da3-11eb-81e6-7ac87540a2c3.png)

**Comment by DiracZhu1998** [comment]
> following

I have same problem trying to rerun the example shown in your tutorial
