### ISSUE TITLE
Errors in running runSCENIC_3_scoreCells(): unable to start device PNG 

### ISSUE THREAD

**Issue by chent5** [aertslab/SCENIC#65]
Hi,

Thanks a lot for developing this package. 

I ran the R script in the Center for Research Computing. I got the error message when running runSCENIC_3_scoreCells() function:
<img width="910" alt="image" src="https://user-images.githubusercontent.com/40006284/52541078-0d4ffe00-2d5f-11e9-8b81-0b89ec3f2d9f.png">

It seems it failed to generate .png files in the Step3_RegulonActivity_tSNE_colByActivity folder.
<img width="996" alt="image" src="https://user-images.githubusercontent.com/40006284/52541059-e09be680-2d5e-11e9-9cc3-1bd4a66fa16c.png">

Could you help to solve this problem? Thank you so much!

**Comment by chent5** [comment]
I have solved this problem.

**Comment by liuyifang** [comment]
I also meet this problem and solved by adding `options(bitmapType = 'cairo')` to R script.

**Comment by iichelhadi** [comment]
> I have solved this problem.

how did you solve the problem?
