### ISSUE TITLE
Database Download and Loading Error

### ISSUE THREAD

**Issue by danielee0707** [aertslab/SCENIC#66]
```
trying URL 'https://resources.aertslab.org/cistarget/databases/homo_sapiens/hg19/refseq_r45/mc9nr/gene_based/hg19-500bp-upstream-7species.mc9nr.feather'
Error in download.file(featherURL, destfile = basename(featherURL)) :
  cannot open URL 'https://resources.aertslab.org/cistarget/databases/homo_sapiens/hg19/refseq_r45/mc9nr/gene_based/hg19-500bp-upstream-7species.mc9nr.feather'
In addition: Warning message:
In download.file(featherURL, destfile = basename(featherURL)) :
  cannot open URL 'https://resources.aertslab.org/cistarget/databases/homo_sapiens/hg19/refseq_r45/mc9nr/gene_based/hg19-500bp-upstream-7species.mc9nr.feather': HTTP status was '403 Forbidden'
```

**Comment by danielee0707** [comment]
Using downloaded databases
```
> scenicOptions <- initializeScenic(org="hgnc", dbDir="databases", nCores=10)
Motif databases selected: 
  hg19-500bp-upstream-7species.mc9nr.feather 
  hg19-tss-centered-10kb-7species.mc9nr.feather
[1] "could not find function \"importRankings\""
[1] "could not find function \"importRankings\""
Warning message:
In initializeScenic(org = "hgnc", dbDir = "databases", datasetTitle = "pbmc",  :
  It was not possible to load the following databses; check whether they are downloaded correctly: 
hg19-500bp-upstream-7species.mc9nr.feather
hg19-tss-centered-10kb-7species.mc9nr.feather

**Comment by s-aibar** [comment]
Dear Danielee,

Indeed, the server hosting the databases is down. 
While we solve the problem you can download the databases from this location: http://bokeh.aertslab.org/cistarget/databases/ (the index is at http://bokeh.aertslab.org/cistarget/, you will need to replace the `resources.` in the links with `bohek.`... ) 

The function "importRankings" is in package RcisTarget, if you do `library(RcisTarget)`before initializeScenic it should work. (I'll also check why isn't it loading automatically...)

Thanks for letting us know!

**Comment by huuthoth** [comment]
Hi,
Could you help me solve this problem
I am trying to download fly database:
dbFiles c("https://resources.aertslab.org/cistarget/databases/drosophila_melanogaster/dm6/flybase_r6.02/mc8nr/gene_based/dm6-5kb-upstream-full-tx-11species.mc8nr.feather")

I got the Warning message: 
cannot open URL 'https://resources.aertslab.org/cistarget/databases/drosophila_melanogaster/dm6/flybase_r6.02/mc8nr/gene_based/dm6-5kb-upstream-full-tx-11species.mc8nr.feather': HTTP status was '500 Internal Server Error'

THANKS

**Comment by ghuls** [comment]
@huuthoth Downloads should be working again.

**Comment by anemartinezlarrinaga2898** [comment]
Hello I get this error when trying to download the databases for the SCENIC analysis: 

In download.file(featherURL, destfile = basename(featherURL)) :
  cannot open URL 'https://resources.aertslab.org/cistarget/databases/mus_musculus/mm9/refseq_r45/mc9nr/gene_based/mm9-500bp-upstream-7species.mc9nr.feather': HTTP status was '404 Not Found'

any help?

**Comment by mikalelhajjar** [comment]
I'm also getting the same 'HTTP status was '404 Not Found' error when I try running:

dbFiles <- c("https://resources.aertslab.org/cistarget/databases/mus_musculus/mm9/refseq_r45/mc9nr/gene_based/mm9-500bp-upstream-7species.mc9nr.feather",
             "https://resources.aertslab.org/cistarget/databases/mus_musculus/mm9/refseq_r45/mc9nr/gene_based/mm9-tss-centered-10kb-7species.mc9nr.feather")

for(featherURL in dbFiles)
{
  download.file(featherURL, destfile=basename(featherURL)) # saved in current dir
}

**Comment by anemartinezlarrinaga2898** [comment]
@mikal16 I solved it download the data manually from the following link: https://resources-mirror.aertslab.org/cistarget/

Check that the file you are downloading is 1GB, and just look for the file names the match with the files the tutorial specifies

**Comment by angelasanzo** [comment]
Hi there,

The links provided now show the 404 not found error, any chance there are others available? 

Many thanks.

**Comment by strawberry098** [comment]
When I run `initializeScenic`, I'm getting the following error in loading the feather files:

`Motif databases selected: 
  hg19-500bp-upstream-7species.mc9nr.feather 
  hg19-tss-centered-10kb-7species.mc9nr.feather
[1] "The index column 'features' is not available in the file."
[1] "The index column 'features' is not available in the file."
Error in initializeScenic(org = org, dbDir = dbDir, dbs = dbs, datasetTitle = myDatasetTitle,  : 
  (converted from warning) It was not possible to load the following databses; check whether they are downloaded correctly: 
hg19-500bp-upstream-7species.mc9nr.feather
hg19-tss-centered-10kb-7species.mc9nr.feather`

In particular, the "features" column is not in the files.
