### ISSUE TITLE
AUCell_exploreThresholds bug

### ISSUE THREAD

**Issue by XiaomeiLi1** [aertslab/SCENIC#69]
When the gene set is not active in all cells (all 0 in auc vector), return error:

Error in if ((sum(histogram[1:5])/sum(histogram)) >= notPopPercent * 0.75) { : 
  missing value where TRUE/FALSE needed

**Comment by s-aibar** [comment]
Dear @XiaomeiLi1 ,
Thank you for the report. This issue was corrected in last update to AUCell.
