### ISSUE TITLE
Metadata mismatch found in `from_delayed`

### ISSUE THREAD

**Issue by zhangbaso** [aertslab/SCENIC#70]
when I ran this code:
with ProgressBar():
    df = prune2df(dbs, modules, MOTIF_ANNOTATIONS_FNAME), a error occurred : 

ValueError: Metadata mismatch found in `from_delayed`.
 columns in the computed data do not match the columns in the provided metadata.
 MultiIndex(levels=[['Enrichment'], ['AUC', 'Annotation', 'Context', 'MotifSimilarityQvalue', 'NES', 'OrthologousIdentity', 'RankAtMax', 'TargetGenes']],
           labels=[[0, 0, 0, 0, 0, 0, 0, 0], [0, 4, 3, 5, 1, 2, 7, 6]])
  :MultiIndex(levels=[['Enrichment'], ['AUC', 'Annotation', 'Context', 'MotifSimilarityQvalue', 'NES', 'OrthologousIdentity', 'RankAtMax', 'TargetGenes']],
           labels=[[0, 0, 0, 0, 0, 0, 0, 0], [0, 1, 2, 3, 4, 5, 6, 7]],
           sortorder=0)

could you please help me to figure out this issue? thank you.

**Comment by s-aibar** [comment]
Dear @zhangbaso , 

Sorry, I am not familiar with the implementation of the python version of SCENIC, but a similar issue was reported at https://github.com/aertslab/pySCENIC/issues/50#issuecomment-461336864 and https://github.com/aertslab/pySCENIC/issues/45#issue-404833993. It seems that the error has something to do with Dask... (please, check those posts for details)

**Comment by zhangbaso** [comment]
> Dear @zhangbaso ,
> 
> Sorry, I am not familiar with the implementation of the python version of SCENIC, but a similar issue was reported at [aertslab/pySCENIC#50 (comment)](https://github.com/aertslab/pySCENIC/issues/50#issuecomment-461336864) and [aertslab/pySCENIC#45 (comment)](https://github.com/aertslab/pySCENIC/issues/45#issue-404833993). It seems that the error has something to do with Dask... (please, check those posts for details)

Dear @s-aibar : thank you very much.it works with no error when I reinstall the dack version 1.0.0 instead of 1.1.1.

**Comment by s-aibar** [comment]
Thanks for letting us know! :)
