### ISSUE TITLE
How to sever the error with all connections are in use?

### ISSUE THREAD

**Issue by wkkion** [aertslab/SCENIC#71]
Hi,
      I'm using the SCENIC_2_createRegulons() function and keep getting the same error: all connection are in use. The detail is:
`runSCENIC_2_createRegulons(scenicOptions)
11:25	Step 2. Identifying regulons
tfModulesSummary:

 top5perTarget top10perTarget           w005 top50perTarget          top50           w001 
           185            291            326            885           1000           1072 
11:25	RcisTarget: Calculating AUC
Scoring database:  [Source file: mm10__refseq-r80__10kb_up_and_down_tss.mc9nr.feather]
12:07	RcisTarget: Adding motif annotation
Number of motifs in the initial enrichment: 781008
Number of motifs annotated to the corresponding TF: 3909
12:18	RcisTarget: Prunning targets
Error in file(con, "w") : all connections are in use`
I googled this error, and used closeAllConnections() before SCENIC_2_createRegulons(), but I still encounter this error in Win10. Can you help out?
Thank you!

**Comment by s-aibar** [comment]
Dear @wkkion ,

This error usually appears when using too many cores... You can try reducing them (down to nCores=1 if needed...)
