### ISSUE TITLE
Adverse correlation between a TF and its regulon: how to explain it?

### ISSUE THREAD

**Issue by WeiCSong** [aertslab/SCENIC#75]
Hi all, i'm working on a single cell dataset with scenic, and i found a weird result: one TF, Atoh1, showed an adverse trend compared to its regulon:

<img width="257" alt="math1-psu" src="https://user-images.githubusercontent.com/41194740/55143814-81f9c300-517a-11e9-9fed-617410b9706f.png">
<img width="381" alt="微信截图_20190311201721" src="https://user-images.githubusercontent.com/41194740/55143843-8f16b200-517a-11e9-8d5e-e8071ab5e9e9.png">

I got target list of Atoh1 from output folder, and found that targets of Atoh1 (i.e Cd47) was positively correlated with Atoh1 regulon, and negatively correlated with Atoh1 itself:

<img width="383" alt="微信截图_20190328165317" src="https://user-images.githubusercontent.com/41194740/55143990-d8670180-517a-11e9-8ebb-edc973ff593a.png">

I'm not familiar with the theories behind GENIE3, and i'm puzzled with this result. How is regulon generated and what give rise to these adverse correlation? Wish to learn from you. Thanks!

**Comment by s-aibar** [comment]
Dear @WeiCSong ,

In principle, SCENIC focuses on the targets that are positively correlated... but it is also possible that some regulons are overall inversely correlated to the TF. For example, if there are subsets of targets that behave different in different cell types... etc... 

To try to understand what is going on more in depth, you can follow/run the steps used to build up that regulon with the "detailed tutorials" (that will also let you doublecheck that there isn't any error on the process, for example that any of the files was read as factors, etc...).


Related question: https://github.com/aertslab/pySCENIC/issues/75
