### ISSUE TITLE
register error in runSCENIC_2_createRegulons

### ISSUE THREAD

**Issue by junjie717** [aertslab/SCENIC#76]
Recently, when I run the scenic pipline, some trouble happened, and I had no idea about this problem. I'm dying for some help. There is the detail information:
```
>runSCENIC_1_coexNetwork2modules(scenicOptions)
20:36	Creating TF modules
Number of links between TFs and targets: 3504334
              [,1]
nTFs          872
nTargets     9437
nGeneSets    4902
nLinks    4257482
>runSCENIC_2_createRegulons(scenicOptions, coexMethod=c("top5perTarget"))
Error in runSCENIC_2_createRegulons(scenicOptions, coexMethod = c("top5perTarget")) : 
Parameters are useless, (coexMethod = c("top5perTarget"))
> runSCENIC_2_createRegulons(scenicOptions)
Error in UseMethod("register", x) : 
"register" has no method "c('MulticoreParam', 'SnowParam', 'BiocParallelParam', 'envRefClass', 
 '.environment', 'refClass', 'environment', 'refObject')" for the target object

```
Anyone have the same error? Please share your solution, Thank you!

**Comment by s-aibar** [comment]
Dear @junjie717 ,

It seems you have to setup your multicore parameters... 
(You can start just by reducing the number of cores... )

**Comment by JovannyChen** [comment]
> Dear @junjie717 ,
> 
> It seems you have to setup your multicore parameters...
> (You can start just by reducing the number of cores... )

Thanks for your reply. However, I have met the same error. [**Error in UseMethod("register", x) : "register" has no method "c('MulticoreParam', 'SnowParam', 'BiocParallelParam', 'envRefClass',  '.environment', 'refClass','environment', 'refObject')" for the target object**]

And I could not solve it by using one core. The friends in my experiment have never met this error. I confirmed that I have loaded all the packages.
library(AUCell)
library(SCENIC)
library(Seurat)
library(doParallel)
library(BiocParallel)
library(rbokeh)
library(mixtools)
library(zoo)
library(rbokeh)
library(DT)
library(NMF)
library(pheatmap)
library(R2HTML)
library(Rtsne)
library(doMC)
library(doRNG)
library(SCopeLoomR)
library(SingleCellExperiment)
library(GENIE3)
library(R2HTML)
library(limma)
library(foreach)
library(methods)
library(tools) 

but: 
> register(MulticoreParam, default = TRUE)
**Error in UseMethod("register", x) : 
  no applicable method for 'register' applied to an object of class "function"**

We used ubuntu18.04, and my friends can run the codes without error, even by using multicores on the same computer.

Best regards,

**Comment by JovannyChen** [comment]
> Recently, when I run the scenic pipline, some trouble happened, and I had no idea about this problem. I'm dying for some help. There is the detail information:
> 
> ```
> >runSCENIC_1_coexNetwork2modules(scenicOptions)
> 20:36	Creating TF modules
> Number of links between TFs and targets: 3504334
>               [,1]
> nTFs          872
> nTargets     9437
> nGeneSets    4902
> nLinks    4257482
> >runSCENIC_2_createRegulons(scenicOptions, coexMethod=c("top5perTarget"))
> Error in runSCENIC_2_createRegulons(scenicOptions, coexMethod = c("top5perTarget")) : 
> Parameters are useless, (coexMethod = c("top5perTarget"))
> > runSCENIC_2_createRegulons(scenicOptions)
> Error in UseMethod("register", x) : 
> "register" has no method "c('MulticoreParam', 'SnowParam', 'BiocParallelParam', 'envRefClass', 
>  '.environment', 'refClass', 'environment', 'refObject')" for the target object
> ```
> 
> Anyone have the same error? Please share your solution, Thank you!

**Comment by junjie717** [comment]
Many thanks, I have solved the problem.

**Comment by mayongshun** [comment]
I met the same problem. How did you solve it? Thank you

**Comment by mayongshun** [comment]
> Many thanks, I have solved the problem.

I met the same problem. How did you solve it? Thank you

**Comment by vida-change** [comment]
How did you solve it? Thank you

**Comment by Jianguowu-git** [comment]
I had the same issue.
> runSCENIC_2_createRegulons(scenicOptions)
Error in UseMethod("register", x) : 
"register" has no method "c('MulticoreParam', 'SnowParam', 'BiocParallelParam', 'envRefClass', 
 '.environment', 'refClass', 'environment', 'refObject')" for the target object
How do you solve this problem? Thanks
