### ISSUE TITLE
Update vignette to use bioconductor 3.9

### ISSUE THREAD

**Issue by Cumol** [aertslab/SCENIC#77]
when running the installation code in this vignette:

https://github.com/aertslab/SCENIC/blob/master/vignettes/SCENIC_Setup.Rmd

It asks for bioconductor 3.8 even though the latest release is 3.9

**Comment by s-aibar** [comment]
Dear @Cumol ,

Thanks for the heads up! 
Bioconductor 3.9 should be fine too, but I still need to double-check it...
