### ISSUE TITLE
update vignette to install github version (runCorrelation missing)

### ISSUE THREAD

**Issue by Cumol** [aertslab/SCENIC#78]
When going through the vignette, I wanted to use runCorrelation, but the function was not found. This appears to be a function that is only present in later versions of SCENIC than the one suggested in the vignette

`devtools::install_github("aertslab/SCENIC", ref="v1.1.0")`

Should probably just be:

`devtools::install_github("aertslab/SCENIC")`

**Comment by s-aibar** [comment]
Thank! This is now updated!
