### ISSUE TITLE
load a loom file converted from a seurat object

### ISSUE THREAD

**Issue by DHGK** [aertslab/SCENIC#79]
Hi SCENIC community,

I was trying to use SCENIC to analyze a proceed data from Seurat. I used as.loom function in Seurat to generate the loom object from my Seurat object. However, when I tried to use "open_loom" to import the object I got this error:
Error in open_loom(loomPath, mode = "r") : unused argument (mode = "r")

If I delete mode = "r", I would have this error:
Error in H5File.open(filename, mode, file_create_pl, file_access_pl) :
  HDF5-API Errors:
    error #000: ../../../src/H5F.c in H5Fopen(): line 591: invalid file name
        class: HDF5
        major: Invalid arguments to routine
        minor: Bad value

I tried several data sets and none of them got successfully imported. Has this issue occurred to anyone before? Would you guys mind sharing a way to fix?

Really appreciate all your help!

**Comment by mase5** [comment]
Hi @DHGK,
You're probably not using the last version of SCopeLoomR
Can you please check what's your current version?
