### ISSUE TITLE
This package introduces too much unnecessary dependencies

### ISSUE THREAD

**Issue by tanpuekai** [aertslab/SCENIC#81]
1, In your latest web [tutorial ](https://rawcdn.githack.com/aertslab/SCENIC/a0a00644b2f3589a3e2bc65486fc5f6cc00f48e1/inst/doc/SCENIC_Running.html#optional_steps:), you said:
```
> loomPath <- system.file(package="SCENIC", "examples/mouseBrain_toy.loom")
> 
> library(SCopeLoomR)
> loom <- open_loom(loomPath, mode="r")
> exprMat <- get_dgem(loom)
> dim(exprMat)
```

Isn't that unnecessary? why would I need to know your what-ever file format? Anyone who knows how to run your crappy script, would know how to prepare an input matrix or whatever built-in format (data.frame, list) for your crappy call function. You just let people know, if they have a gene-by-cell table of data, how do they get started, using R's built-in data formats. ok? No one has any interest in learning your crappy thing.

2. You have too many crappy functions, like `plotTsne_AUCellApp()`, `tsneAUC()`, `plotTsne_compareSettings()`, `Cairo::CairoPDF()`, `plotTsne_rgb()`, `pheatmap::pheatmap()`. 

why would we need to learn these crappy functions, when they add nothing more than R's built-in functions are capable of doing? Why can't you just give a table of whatever your crappy software produces per cell or per gene, or per cluster, to a table variable, and let ppl manipulate it freely using R's built-in functions?

**Comment by tanpuekai** [comment]
You said:
```
tSNE_scenic <- readRDS(tsneFileName(scenicOptions))
aucell_regulonAUC <- loadInt(scenicOptions, "aucell_regulonAUC")

# Show TF expression:
par(mfrow=c(2,3))
AUCell::AUCell_plotTSNE(tSNE_scenic$Y, exprMat, aucell_regulonAUC[onlyNonDuplicatedExtended(rownames(aucell_regulonAUC))[c("Dlx5", "Sox10", "Sox9","Irf1", "Stat6")],], plots="Expression")
```


It turns out your variable `aucell_regulonAUC` is a completely non-directly accessible creepy variable. why would we need to learn this stupid format anyway? why can't you store it in a simple `matrix`, `data.frame` format?

**Comment by s-aibar** [comment]
Indeed, you don't need any of those functions. You can just run the plots and t-SNEs manually.
