### ISSUE TITLE
Error in runSCENIC_2_createRegulons (Feather file footer incomplete)

### ISSUE THREAD

**Issue by justinesjw** [aertslab/SCENIC#83]
Hi! 

Thanks for building SCENIC, been helping alot in my research.

However I have been having trouble loading the feather database when I run step 2.
```
runSCENIC_2_createRegulons(scenicOptions)
12:04   Step 2. Identifying regulons
Error in openFeather(path) : Invalid: Feather file footer incomplete
```

I tried running line by line in `runSCENIC_2_createRegulons`
the error pop up in 
`suppressMessages(motifRankings <- lapply(getDatabases(scenicOptions),importRankings))`

then i ran lines in `importRankings`
and found the error in

```
rnks <- feather::read_feather(dbFile, columns = columns)
Error in openFeather(path) : Invalid: Feather file footer incomplete
```

I have found a same error here:
https://github.com/wesm/feather/issues/248
but could not find a solution to it. 

Here is my sessionInfo :
![image](https://user-images.githubusercontent.com/26448066/59171315-030b0880-8b75-11e9-8c4d-78ce0a31bac5.png)
![image](https://user-images.githubusercontent.com/26448066/59171330-1918c900-8b75-11e9-82dc-46272776f699.png)

Would be grateful with some help

Thanks, 
Justine

**Comment by s-aibar** [comment]
Dear @justinesjw ,

Errors reading the databases usually happens when the files are incomplete/corrupt (e.g. by a failed download).

We recommended to download the databases is using zsync_curl (https://resources.aertslab.org/cistarget/help.html). Once you have the files, make sure the sha256sum match the reported ones (https://resources.aertslab.org/cistarget/databases/sha256sum.txt). 

Can you let me know whether this helps?

Thanks!

**Comment by justinesjw** [comment]
Hi @s-aibar,

I redownloaded the databases but the sha256sum does not match. 
![image](https://user-images.githubusercontent.com/26448066/59331103-a8fd7500-8d25-11e9-9d8a-b6a12a949669.png)

besides that, my R session get aborted spontaneously at the same line at `importRankings`
![image](https://user-images.githubusercontent.com/26448066/59331205-f1b52e00-8d25-11e9-90c2-5a7dac310acb.png)

Please advise.

Thanks, 
Justine

**Comment by justinesjw** [comment]
Oh! 

Found this --> https://github.com/aertslab/SCENIC/issues/42

Working on it. Thanks!

**Comment by justinesjw** [comment]
Hi @s-aibar ,

Thank you so much for your help. 

I was not able to use `zsync_curl` as i do not have the admin rights to my workstation to set up `zsync_curl` but `curl -O` works just fine. 

sha256sum matched!

Best,
Justine
