### ISSUE TITLE
Which assay should I use?

### ISSUE THREAD

**Issue by anyone1985** [aertslab/SCENIC#84]
Hi,

I'm using Seurat to deal with my data. I'd like to convert to loom object with as.loom. I'd like to know which assay I should use? RNA (raw count)? or SCT (Normalized with SCTransform)?

Best wishes

**Comment by s-aibar** [comment]
Dear @anyone1985 ,

We don't have any specific recommendation as to what assay to use. In general we haven't observed very strong differences when using the raw or the normalized counts.

Related explanation in the Setup tutorial: 
```
Expression units: The preferred expression values are gene-summarized counts (which might or might not use unique molecular identifiers, UMI). Other measurements, such as counts or transcripts per million (TPM) and FPKM/RPKM, are also accepted as input. However, note that some authors recommend avoiding within sample normalization (i.e. TPM) for co-expression analysis (first step of SCENIC) because they may induce artificial co-variation (Crow et al. (2016)). Although more work is still needed in order to determine the best normalization approach (Vallejos et al. (2017)), we have applied SCENIC to datasets using raw (logged) UMI counts, normalized UMI counts, and TPM and all of them provided reliable results (see Aibar et al. (2017)). The remaining steps of the workflow should not be affected by the expression units/normalization, as the expression is not taken into account for the motif analysis, and AUCell is within-cell ranking-based (wich works as an implicit normalization).
```

**Comment by panxiaoguang** [comment]
> Hi,
> 
> I'm using Seurat to deal with my data. I'd like to convert to loom object with as.loom. I'd like to know which assay I should use? RNA (raw count)? or SCT (Normalized with SCTransform)?
> 
> Best wishes

Hello，I want to know what assay you use in your step?RNA or Integrated? I always use integrated data to analyse some function ,such as GSVA && SCENIC TF analysis, but can not got more 
effective result? what's your oppion?
