### ISSUE TITLE
Issue installing SCENIC 1.1.2-01

### ISSUE THREAD

**Issue by sanjeevRJMU1** [aertslab/SCENIC#85]
Having an issue installing SCENIC (screen shot attached). Was able to install AUCell, Rcistarget, and GENIE3 and have updated my R to 3.6.0. Any help would be appreciated!
<img width="823" alt="Screen Shot 2019-06-11 at 6 42 17 AM" src="https://user-images.githubusercontent.com/26235762/59277220-a5c69400-8c14-11e9-9344-dd656685c2bd.png">

**Comment by sanjeevRJMU1** [comment]
I've also tried devtools::install_github("aertslab/SCENIC"), without the ref="v1.1.0" and I get the same error...

**Comment by s-aibar** [comment]
Dear @sanjeevRJMU1 ,

If you have R 3.6, you can indeed use  `devtools::install_github("aertslab/SCENIC")` (the current version is ready for R 3.6). 

It seems you are missing the package "SingleCellExperiment", you can try to install it individually (to see whether it gives any error/solves the problem). If you installed some packages before updating R to 3.6 that might be the source of the issue... (you might need to update them to the latest version -especially the ones in Bioconductor-).

Does that help?

**Comment by sanjeevRJMU1** [comment]
Yes thank you!! I installed the missing package SingleCellExperiment before installing SCENIC:
http://bioconductor.org/packages/release/bioc/html/SingleCellExperiment.html

now I'm all set. Thank you again!
