### ISSUE TITLE
Unable to install SCopeLoomR 

### ISSUE THREAD

**Issue by yxiao832** [aertslab/SCENIC#86]
Hi SCENIC team, 
I can't install SCopeLoomR in our HPC-PMACS because we are missing GLIBCXX_3.4.21. 
I wonder whether there is a way I can use SCENIC without SCopeLoomR? 
It seems in the old version  the input file format are not restricted to loom?
Thank you!
Yang

**Comment by s-aibar** [comment]
Dear @yxiao832 ,

Yes, SCopeLoomR is mostly required to import/export data to .loom files. If you can/want to save it in other formats, you don't need it.
