### ISSUE TITLE
Error in corrMat[tf, targets]: subscript out of bounds

### ISSUE THREAD

**Issue by rjb67** [aertslab/SCENIC#87]
I am currently running through SCENIC and have encountered an issue when I try to run 

`runSCENIC_1_coexNetwork2modules(scenicOptions)`

When I run this after following through the steps in the vignette, I get this error:

`Error in corrMat[tf, targets] : subscript out of bounds
In addition: Warning message:
In runSCENIC_1_coexNetwork2modules(scenicOptions) :
  The following TFs are missing from the correlation matrix: 2010315B03Rik, 2610044O15Rik8, Ak6, Akr1a1, B230307C23Rik, Borcs8, Cers2, Cers4, Cers5, Cers6, Cptp, Exo5, Faap24, Foxf1, Gm10053, Gm10093, Gm10269, Gm12184, Gm14305, Gm14322, Gm14399, Gm14418, Gm14419, Gm14443, Gm15446, Gm17655, Gm2000, Gm20939, Gm35315, Gm38394, Gm45871, Gm4631, Hnrnpll, Kdm7a, Kmt2a, Mief1, Mterf1a, Mterf1b, Mycl, Nelfa, Nelfb, Nelfe, Noc2l, Pkm, Pum3, Rbm8a2, Spi1, Supt20, Tcf24, Tfap4, Tfcp2, Tfe3, Tfeb, Tfec, Thap12, Trmo, Zbtb14, Zbtb18, Zfp24, Zfp383, Zfp607a, Zfp607b, Zfp626, Zfp729a, Zfp729b, Zfp850, Zfp950, Zfp965, Zfp966, Zfp970, Zfp971, Zfp973, Zfp974, Zfp975, Zfp976, Zkscan7, Zkscan8, Zscan25, Zscan26`

What could be the cause of this error?

Edit: I realized the problem! I forgot to actually use the filtered expression matrix.

**Comment by Tianqi-Ma** [comment]
For me, it was because the expression matrix used for SCENIC pipeline was different with the one for grnboost2. So i was using pySCENIC grnboost2 function to generate the co-expression network and then imported it into int folder to continue the rest part using SCENIC pipeline. I forgot to change the raw expression matrix to the one i put into pySCENIC.

**Comment by trucnguyen89** [comment]
> I am currently running through SCENIC and have encountered an issue when I try to run
> 
> `runSCENIC_1_coexNetwork2modules(scenicOptions)`
> 
> When I run this after following through the steps in the vignette, I get this error:
> 
> `Error in corrMat[tf, targets] : subscript out of bounds In addition: Warning message: In runSCENIC_1_coexNetwork2modules(scenicOptions) : The following TFs are missing from the correlation matrix: 2010315B03Rik, 2610044O15Rik8, Ak6, Akr1a1, B230307C23Rik, Borcs8, Cers2, Cers4, Cers5, Cers6, Cptp, Exo5, Faap24, Foxf1, Gm10053, Gm10093, Gm10269, Gm12184, Gm14305, Gm14322, Gm14399, Gm14418, Gm14419, Gm14443, Gm15446, Gm17655, Gm2000, Gm20939, Gm35315, Gm38394, Gm45871, Gm4631, Hnrnpll, Kdm7a, Kmt2a, Mief1, Mterf1a, Mterf1b, Mycl, Nelfa, Nelfb, Nelfe, Noc2l, Pkm, Pum3, Rbm8a2, Spi1, Supt20, Tcf24, Tfap4, Tfcp2, Tfe3, Tfeb, Tfec, Thap12, Trmo, Zbtb14, Zbtb18, Zfp24, Zfp383, Zfp607a, Zfp607b, Zfp626, Zfp729a, Zfp729b, Zfp850, Zfp950, Zfp965, Zfp966, Zfp970, Zfp971, Zfp973, Zfp974, Zfp975, Zfp976, Zkscan7, Zkscan8, Zscan25, Zscan26`
> 
> What could be the cause of this error?
> 
> Edit: I realized the problem! I forgot to actually use the filtered expression matrix.

Hi,

I'm currently running SCENIC and also encountered this error.
I found that you could fix the problem using the filtered expression matrix but I don't really get it. How could I put the filtered expression matrix into this command, or how exactly can I fix this error? 
Thank you so much in advance!

**Comment by YogiBud** [comment]
Hi,
I ran into the same error before, and in my case it was related to running the SCENIC pipeline inside a loop. SCENIC is somewhat hard-coded and automatically creates its own output folders, intermediate files, and figures. When you run it in a loop without changing directories, each iteration can overwrite/reuse files from the previous run. As a result, SCENIC may end up reusing or reading files that do not correspond to the current dataset, which can lead to errors like above.
