### ISSUE TITLE
RcisTarget dataset download error

### ISSUE THREAD

**Issue by Ian2696** [aertslab/SCENIC#91]
I’m looking to use your SCENIC package to analyse our 10X scRNA-seq dataset. However upon trying to download the species-specific databases for RcisTarget I am getting the following error:  HTTP status was ‘403 Forbidden’ . 

I get the same error when I also try to access the 'https://resources.aertslab.org/cistarget/‘ webpage. 

Please could you advise how I would be able to download these datasets. Thanks in advance for any help you can provide.

**Comment by haircell** [comment]
Hi, I'm also getting the same error:
"Forbidden

You don't have permission to access /cistarget/ on this server."

This happens whenever I try to access "https://resources.aertslab.org/cistarget/"
I tried downloading the RcisTarget databases for mouse from R and Terminal without success (or manually by going to the Aerts Lab website. Any help would be greatly appreciated.

Thanks!

**Comment by 1746252547** [comment]
With some thing to me.

**Comment by haircell** [comment]
It seems that I'm now able to go to https://resources.aertslab.org/cistarget/

But when I try to download any of the databases, I get the following server error:
"Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at [no address given] to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log."

**Comment by ghuls** [comment]
@haircell It should be working now.

**Comment by haircell** [comment]
Thank you, @ghuls !
It works now :)

**Comment by 1746252547** [comment]
I stacked in the step ' initializeScenic(org=org, dbDir=dbDir, dbs=dbs, datasetTitle=myDatasetTitle) 
'
After running this, the R session aborted. And error is 'This Feather file is old and will not be readable beyond the 0.3.0 release'

Have you encountered this problem? Is it a problem about the feather or the memory of R in my server?

Thanks!

**Comment by s-aibar** [comment]
An alternative mirror for downloading the RcisTarget databases and annotation files is available at: https://resources-mirror.aertslab.org/cistarget/

(in case there are problems with the main server again...)
